import { Request, Response, NextFunction } from 'express';
import { createHash, randomUUID } from 'node:crypto';
import IORedis from 'ioredis';
import { adminAuth } from '../lib/firebase-admin.ts';
import { config } from '../config.ts';
import { db } from '../db/index.ts';
import { users } from '../db/schema.ts';
import { eq } from 'drizzle-orm';
import { attachTenantScope, ScopedDb } from './tenant-scope.ts';
import { recordSession } from '../security/session-tracking.ts';
import { capabilityDenial, capabilityForPath, evaluateCapability } from '../security/entitlements.ts';
export interface AuthenticatedRequest extends Request { user?: { id: number; uid: string; email: string; tenantId: string; role: string; clientId: string | null; emailVerified: boolean }; db?: ScopedDb; }
let rateLimitWindowMs = 60_000; let maxRequestsPerWindow = 100; const isTestMode = () => process.env.NODE_ENV !== 'production';
export function setRateLimiterConfig(opts: { windowMs?: number; maxRequests?: number }) { if (!isTestMode()) throw new Error('setRateLimiterConfig is only available in test mode'); if (typeof opts.windowMs === 'number' && opts.windowMs > 0) rateLimitWindowMs = opts.windowMs; if (typeof opts.maxRequests === 'number' && opts.maxRequests > 0) maxRequestsPerWindow = Math.floor(opts.maxRequests); }
interface RateLimitRecord { count: number; resetAt: number; } interface RateLimitStore { incr(key: string, windowMs: number, limit: number): Promise<RateLimitRecord>; }
class InMemoryStore implements RateLimitStore { private map = new Map<string, RateLimitRecord>(); async incr(key: string, windowMs: number, _limit: number) { const now = Date.now(); const rec = this.map.get(key); if (!rec || now >= rec.resetAt) { const next = { count: 1, resetAt: now + windowMs }; this.map.set(key, next); return next; } rec.count += 1; return rec; } }
interface AtomicRateLimitClient { increment(script: string, key: string, windowMs: number, limit: number): Promise<unknown>; }
export class IORedisAtomicClient implements AtomicRateLimitClient { constructor(private readonly client: { eval(script: string, numKeys: number, ...args: Array<string | number>): Promise<unknown> }) {} increment(script: string, key: string, windowMs: number, limit: number) { return this.client.eval(script, 1, key, String(windowMs), String(limit)); } }
export function createAtomicRateLimitClient(provider: 'ioredis', client: any): AtomicRateLimitClient { if (provider === 'ioredis' && client && typeof client.eval === 'function') return new IORedisAtomicClient(client); throw new Error('Invalid or unsupported rate limit provider'); }
export class RedisStore implements RateLimitStore { private readonly lua = `local count = redis.call("INCR", KEYS[1])\nlocal ttl = redis.call("PTTL", KEYS[1])\nif count == 1 or ttl < 0 then redis.call("PEXPIRE", KEYS[1], ARGV[1]) ttl = tonumber(ARGV[1]) end\nreturn {count, ttl}`; constructor(private readonly atomicClient: AtomicRateLimitClient) {} async incr(key: string, windowMs: number, limit: number) { const res = await this.atomicClient.increment(this.lua, key, windowMs, limit); if (!Array.isArray(res) || res.length < 2) throw new Error('Unexpected Redis rate-limit response'); const count = Number(res[0]); const ttl = Number(res[1]); if (!Number.isFinite(count) || count < 0 || !Number.isFinite(ttl) || ttl <= 0) throw new Error('Invalid Redis rate-limit response'); return { count, resetAt: Date.now() + ttl }; } }
let sharedStore: RateLimitStore = new InMemoryStore();
export function createSharedRateLimitStoreFromEnv(): RateLimitStore { if (!config.isProduction) return new InMemoryStore(); if (!config.redis.url) throw new Error('REDIS_URL is required for production rate limiting'); const client = new IORedis(config.redis.url, { lazyConnect: true, enableReadyCheck: true, maxRetriesPerRequest: 2, connectTimeout: 5000, commandTimeout: 5000, retryStrategy: (times: number) => Math.min(times * 250, 2000) }); client.on('error', (err: Error) => console.error('[RateLimiter] Redis error:', err.message)); client.on('ready', () => console.info('[RateLimiter] Redis ready')); client.on('end', () => console.error('[RateLimiter] Redis connection ended; requests will fail closed')); void client.connect().catch((err: Error) => console.error('[RateLimiter] Redis initial connection failed:', err.message)); return new RedisStore(createAtomicRateLimitClient('ioredis', client)); }
if (config.isProduction) sharedStore = createSharedRateLimitStoreFromEnv(); export function setRateLimiterStore(s: RateLimitStore) { if (!isTestMode()) throw new Error('setRateLimiterStore is only available in test mode'); sharedStore = s; }
function budgetFor(req: Request) { const path = req.path.toLowerCase(); if (path.includes('/scan') || path.includes('/monitoring') || path.includes('/reports') || path.includes('/passport')) return { windowMs: 60_000, max: 20, className: 'expensive' }; if (path.includes('/webhook') || path.includes('/integration') || path.includes('/v1')) return { windowMs: 60_000, max: 60, className: 'api' }; if (req.method !== 'GET' && req.method !== 'HEAD' && req.method !== 'OPTIONS') return { windowMs: 60_000, max: 40, className: 'mutation' }; return { windowMs: rateLimitWindowMs, max: maxRequestsPerWindow, className: 'default' }; }
function limiterIdentity(req: Request) { const ip = req.ip || req.socket.remoteAddress || 'unknown'; const apiKey = typeof req.headers['x-api-key'] === 'string' ? req.headers['x-api-key'].trim() : ''; const bearer = typeof req.headers.authorization === 'string' ? req.headers.authorization.trim() : ''; const credential = apiKey || bearer; const credentialFingerprint = credential ? createHash('sha256').update(credential, 'utf8').digest('hex').slice(0, 32) : ''; return { ip, credentialFingerprint }; }
export const rateLimiter = async (req: Request, res: Response, next: NextFunction) => { const budget = budgetFor(req); const { ip, credentialFingerprint } = limiterIdentity(req); const identity = credentialFingerprint ? `ip:${ip}:credential:${credentialFingerprint}` : `ip:${ip}`; try { const counter = await sharedStore.incr(`rl:v3:${budget.className}:${identity}`, budget.windowMs, budget.max); res.setHeader('X-RateLimit-Limit', String(budget.max)); res.setHeader('X-RateLimit-Remaining', String(Math.max(0, budget.max - counter.count))); res.setHeader('X-RateLimit-Reset', String(Math.ceil(counter.resetAt / 1000))); res.setHeader('X-RateLimit-Policy', `${budget.max};w=${Math.ceil(budget.windowMs / 1000)};class=${budget.className}`); if (counter.count > budget.max) { const retryAfter = Math.max(1, Math.ceil((counter.resetAt - Date.now()) / 1000)); res.setHeader('Retry-After', String(retryAfter)); return res.status(429).json({ error: { code: 'RATE_LIMITED', message: 'Too many requests.' } }); } return next(); } catch (err) { const requestId = randomUUID(); console.error('[RateLimiter] fail-closed (requestId=%s): %s', requestId, err instanceof Error ? err.message : String(err)); return res.status(503).json({ error: { code: 'RATE_LIMIT_STORE_UNAVAILABLE', message: 'This operation is temporarily unavailable.', requestId } }); } };
const BILLING_EXEMPT_PATHS = ['/api/billing','/api/user/me','/api/auth/resend-verification','/api/auth/verify-status'] as const;
function isBillingExemptPath(req: Request): boolean { const path = `${req.baseUrl}${req.path}`.replace(/\/$/, '') || '/'; return BILLING_EXEMPT_PATHS.some(allowed => path === allowed || path.startsWith(`${allowed}/`)); }
export async function enforcePaidAccess(req: AuthenticatedRequest, res: Response): Promise<boolean> { if (isBillingExemptPath(req)) return true; const tenantId = req.user?.tenantId; const scopedDb = req.db; if (!tenantId || !scopedDb) { res.status(403).json({ error: 'SUBSCRIPTION_REQUIRED', code: 'SUBSCRIPTION_REQUIRED', message: 'An authenticated workspace is required.' }); return false; } const capability = capabilityForPath(req); const decision = await evaluateCapability(scopedDb, tenantId, capability); if (!decision.allowed) { res.status(402).json(capabilityDenial(capability, decision)); return false; } res.locals.billing = { plan: decision.state.plan, status: decision.state.status, currentPeriodEnd: decision.state.currentPeriodEnd, capability, gate: decision.gate }; return true; }
const VALID_ROLES = new Set(['Owner', 'Admin', 'Technician', 'Viewer', 'Client']);
export const requireAuth = async (req: AuthenticatedRequest, res: Response, next: NextFunction) => { const authHeader = req.headers.authorization; const token = authHeader?.startsWith('Bearer ') ? authHeader.slice(7).trim() : ''; if (!token || token.length > 8192) return res.status(401).json({ error: 'Unauthorized: Missing or invalid authorization token' }); try { const decodedToken = await adminAuth.verifyIdToken(token, true); const uid = decodedToken.uid; if (!uid || typeof uid !== 'string' || uid.length > 256) return res.status(401).json({ error: 'Unauthorized: Invalid security token' }); const isVerificationExemptPath = ['/api/user/me','/api/auth/resend-verification','/api/auth/verify-status'].includes(req.baseUrl + req.path); const emailVerified = decodedToken.email_verified === true; if (!emailVerified && !isVerificationExemptPath) return res.status(403).json({ error: 'Email verification required', code: 'EMAIL_NOT_VERIFIED' }); const dbUser = await db.select().from(users).where(eq(users.uid, uid)).then(rows => rows[0]); if (!dbUser) return res.status(403).json({ error: 'User account is not provisioned' }); if (!dbUser.tenantId || dbUser.tenantId.length > 256) return res.status(403).json({ error: 'User account has invalid tenant configuration' }); if (!dbUser.role || dbUser.role.length > 64 || !VALID_ROLES.has(dbUser.role)) return res.status(403).json({ error: 'User account has invalid role configuration' }); if (dbUser.role === 'Client' && !dbUser.clientId) return res.status(403).json({ error: 'Client account has invalid client configuration' }); const dbEmail = dbUser.email.trim().toLowerCase(); const tokenEmail = typeof decodedToken.email === 'string' ? decodedToken.email.trim().toLowerCase() : ''; if (tokenEmail && dbEmail && tokenEmail !== dbEmail) return res.status(403).json({ error: 'User identity does not match the provisioned account' }); req.user = { id: dbUser.id, uid, email: dbUser.email, tenantId: dbUser.tenantId, role: dbUser.role, clientId: dbUser.clientId ?? null, emailVerified }; req.db = await attachTenantScope(dbUser.tenantId, res, dbUser.id); if (!(await enforcePaidAccess(req, res))) return; const ip = req.ip || req.socket.remoteAddress || 'unknown'; const userAgent = typeof req.headers['user-agent'] === 'string' ? req.headers['user-agent'].slice(0, 512) : ''; try { await recordSession(req.db, { tenantId: dbUser.tenantId, userId: dbUser.id, uid, ip, userAgent }); } catch (err) { console.error('[Session] recordSession failed:', err instanceof Error ? err.message : String(err)); } return next(); } catch (err) { if (err && typeof err === 'object' && 'code' in err && (err as { code?: string }).code === 'auth/id-token-revoked') return res.status(401).json({ error: 'Unauthorized: Session revoked', code: 'SESSION_REVOKED' }); return res.status(401).json({ error: 'Unauthorized: Invalid or expired security token' }); } };
export function requireRole(roles: string | string[]) { const allowedRoles = Array.isArray(roles) ? roles : [roles]; return (req: AuthenticatedRequest, res: Response, next: NextFunction) => { if (!req.user) return res.status(401).json({ error: 'Unauthorized' }); if (allowedRoles.length > 0 && !allowedRoles.includes(req.user.role)) return res.status(403).json({ error: 'Forbidden' }); return next(); }; }
