import { Router } from 'express';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import crypto from 'node:crypto';
import { requireAuth, requireRole, AuthenticatedRequest } from '../middleware/security.ts';
import { INTEGRATION_CATALOG } from '../integrations/catalog.ts';

const providers=new Set(INTEGRATION_CATALOG.map(x=>x.provider));
const schema=z.object({clientId:z.string().min(1).max(200),assetId:z.string().min(1).max(200),passportId:z.string().min(1).max(200),provider:z.string().min(1).max(64),credentialReferenceId:z.string().min(1).max(200),scheduleSeconds:z.number().int().min(900).max(2592000).default(3600)}).strict();
function id(p:string){return`${p}_${crypto.randomUUID().replaceAll('-','')}`;}
export function createIntegrationMonitoringRouter(){const router=Router();router.use(requireAuth);
 router.post('/configurations',requireRole(['Admin']),async(req:AuthenticatedRequest,res,next)=>{try{const db=req.db!;const p=schema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'VALIDATION_ERROR',details:p.error.flatten()});if(!providers.has(p.data.provider))return res.status(400).json({error:'PROVIDER_NOT_SUPPORTED'});const passport=(await db.execute(sql`SELECT id FROM passports WHERE id=${p.data.passportId} AND tenant_id=${req.user!.tenantId} LIMIT 1`) as any).rows?.[0];if(!passport)return res.status(404).json({error:'PASSPORT_NOT_FOUND'});const credential=(await db.execute(sql`SELECT id FROM credential_references WHERE id=${p.data.credentialReferenceId} AND tenant_id=${req.user!.tenantId} AND state='active' LIMIT 1`) as any).rows?.[0];if(!credential)return res.status(404).json({error:'CREDENTIAL_REFERENCE_NOT_FOUND'});const now=new Date().toISOString();const configId=id('monitor');await db.execute(sql`INSERT INTO monitoring_configurations (id,tenant_id,client_id,asset_id,passport_id,collector_id,subject_type,subject_identifier,enabled,schedule_seconds,next_scheduled_at,credential_reference_id,last_status,freshness_policy_id,confidence_policy_id,created_by,updated_by,created_at,updated_at) VALUES (${configId},${req.user!.tenantId},${p.data.clientId},${p.data.assetId},${p.data.passportId},${p.data.provider},'integration_provider',${p.data.provider},1,${p.data.scheduleSeconds},${now},${p.data.credentialReferenceId},'unknown','integration.v1','observed.v1',${req.user!.uid},${req.user!.uid},${now},${now})`);return res.status(201).json({id:configId,provider:p.data.provider,scheduleSeconds:p.data.scheduleSeconds,enabled:true});}catch(e){return next(e);}});
 router.get('/configurations',async(req:AuthenticatedRequest,res,next)=>{try{const db=req.db!;const isClient=req.user!.role==='Client';const clientId=req.user!.clientId;if(isClient&&!clientId)return res.status(403).json({error:'Client account has invalid client configuration'});const rows=await db.execute(sql`SELECT id,client_id,asset_id,passport_id,collector_id AS provider,enabled,schedule_seconds,next_scheduled_at,last_successful_at,last_status,credential_reference_id,created_at,updated_at FROM monitoring_configurations WHERE tenant_id=${req.user!.tenantId} AND subject_type='integration_provider' AND (${isClient ? sql`client_id = ${clientId}` : sql`TRUE`}) ORDER BY updated_at DESC`);return res.json({configurations:(rows as any).rows||[]});}catch(e){return next(e);}});
 return router;}
