import { Router } from 'express';
import { sql } from 'drizzle-orm';
import { z } from 'zod';
import crypto from 'node:crypto';
import { db } from '../db/index.ts';
import { requireAuth, AuthenticatedRequest } from '../middleware/security.ts';
import { decryptCredentials } from '../integrations/credential-vault.ts';
import { collectDeepProviderEvidence } from '../integrations/deep-collectors.ts';
import { persistTrustLoop, verifyRemediation } from '../trust/trust-loop.ts';

const collectSchema=z.object({passportId:z.string().trim().min(1).max(255),provider:z.string().trim().min(1).max(64)}).strict();
const remediationSchema=z.object({findingId:z.string().trim().min(1),title:z.string().trim().min(1).max(255),description:z.string().max(4000).optional(),assigneeId:z.string().max(255).optional(),priority:z.enum(['LOW','MEDIUM','HIGH','CRITICAL']).default('HIGH')}).strict();
const verifySchema=z.object({findingId:z.string().trim().min(1),observationIds:z.array(z.string().min(1)).max(50),evidenceIds:z.array(z.string().min(1)).max(200)}).strict();
function id(p:string){return `${p}_${crypto.randomUUID().replaceAll('-','')}`;}

export function createTrustLoopRouter(){const router=Router();
 router.post('/collect',requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const p=collectSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_PAYLOAD',details:p.error.flatten()});const tenantId=req.user!.tenantId;const passport=(await db.execute(sql`SELECT id,client_id FROM passports WHERE id=${p.data.passportId} AND tenant_id=${tenantId} LIMIT 1`) as any).rows?.[0];if(!passport)return res.status(404).json({error:'PASSPORT_NOT_FOUND'});const stored=(await db.execute(sql`SELECT encrypted_payload FROM integration_credentials WHERE tenant_id=${tenantId} AND provider=${p.data.provider} LIMIT 1`) as any).rows?.[0];if(!stored?.encrypted_payload)return res.status(409).json({error:'CREDENTIAL_NOT_CONFIGURED'});const credentials=decryptCredentials(stored.encrypted_payload) as Record<string,string>;const observations=await collectDeepProviderEvidence(p.data.provider as any,credentials);const result=await persistTrustLoop({tenantId,passportId:passport.id,clientId:passport.client_id||passport.id,assetId:passport.id,observations});return res.json({provider:p.data.provider,observationCount:observations.length,...result});}catch(e){return next(e);}});
 router.get('/findings',requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const tenantId=req.user!.tenantId;const passportId=typeof req.query.passportId==='string'?req.query.passportId:null;const rows=passportId?await db.execute(sql`SELECT * FROM trust_findings WHERE tenant_id=${tenantId} AND passport_id=${passportId} ORDER BY CASE severity WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 WHEN 'low' THEN 4 ELSE 5 END, updated_at DESC`):await db.execute(sql`SELECT * FROM trust_findings WHERE tenant_id=${tenantId} ORDER BY updated_at DESC`);return res.json({findings:(rows as any).rows||[]});}catch(e){return next(e);}});
 router.post('/remediations',requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const p=remediationSchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_PAYLOAD',details:p.error.flatten()});const tenantId=req.user!.tenantId;const finding=(await db.execute(sql`SELECT id,client_id,passport_id,title,description FROM trust_findings WHERE id=${p.data.findingId} AND tenant_id=${tenantId} LIMIT 1`) as any).rows?.[0];if(!finding)return res.status(404).json({error:'FINDING_NOT_FOUND'});const now=new Date().toISOString();const taskId=id('remed');await db.execute(sql`INSERT INTO remediation_tasks (id,tenant_id,client_id,alert_id,title,description,priority,status,assignee_id,created_by,created_at,updated_at) VALUES (${taskId},${tenantId},${finding.client_id},${finding.id},${p.data.title},${p.data.description||finding.description},${p.data.priority},'OPEN',${p.data.assigneeId||null},${req.user!.uid},${now},${now})`);return res.status(201).json({id:taskId,findingId:finding.id,status:'OPEN'});}catch(e){return next(e);}});
 router.post('/verify',requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const p=verifySchema.safeParse(req.body);if(!p.success)return res.status(400).json({error:'INVALID_PAYLOAD',details:p.error.flatten()});const result=await verifyRemediation({tenantId:req.user!.tenantId,findingId:p.data.findingId,observationIds:p.data.observationIds,evidenceIds:p.data.evidenceIds,actorId:req.user!.uid});return res.json(result);}catch(e){return next(e);}});
 router.get('/ledger/:passportId',requireAuth,async(req:AuthenticatedRequest,res,next)=>{try{const tenantId=req.user!.tenantId;const passportId=req.params.passportId;const observations=await db.execute(sql`SELECT id,observation_version,generated_at,previous_observation_id,evidence_ids,finding_ids,canonical_payload_hash,completeness_basis_points,open_finding_count,unknown_dimension_count FROM trust_observations WHERE tenant_id=${tenantId} AND passport_id=${passportId} ORDER BY observation_version DESC`);const evidence=await db.execute(sql`SELECT id,provider,control_id,subject,source_url,observed_at,verification_method,status,severity,evidence_hash,limitation FROM evidence_ledger WHERE tenant_id=${tenantId} AND passport_id=${passportId} ORDER BY observed_at DESC`);const findings=await db.execute(sql`SELECT id,control_id,title,severity,status,evidence_ids,fingerprint,updated_at,resolved_at FROM trust_findings WHERE tenant_id=${tenantId} AND passport_id=${passportId} ORDER BY updated_at DESC`);return res.json({observations:(observations as any).rows||[],findings:(findings as any).rows||[],evidence:(evidence as any).rows||[]});}catch(e){return next(e);}});
 return router;}
