import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const root = process.cwd();
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')) as {
  private: boolean; version: string; license: string; engines: { node: string }; packageManager: string;
  scripts: Record<string,string>; dependencies: Record<string,string>; devDependencies: Record<string,string>;
  overrides: Record<string,unknown>;
};
const ci = readFileSync(resolve(root, '.github/workflows/ci.yml'), 'utf8');
const worker = readFileSync(resolve(root, 'src/workers/distribution-worker.ts'), 'utf8');

const checks: Array<[string, () => void]> = [
  ['01 package is private', () => expect(pkg.private).toBe(true)],
  ['02 Node major is constrained to 22', () => expect(pkg.engines.node).toBe('>=22 <23')],
  ['03 npm version is pinned', () => expect(pkg.packageManager).toBe('npm@10.9.2')],
  ['04 production build script exists', () => expect(pkg.scripts.build).toContain('vite build')],
  ['05 production start uses bundled server', () => expect(pkg.scripts.start).toContain('node dist/server.cjs')],
  ['06 worker uses bundled worker', () => expect(pkg.scripts.worker).toContain('node dist/worker.cjs')],
  ['07 typecheck script exists', () => expect(pkg.scripts.typecheck).toBe('tsc --noEmit')],
  ['08 test script is Vitest', () => expect(pkg.scripts.test).toBe('vitest run')],
  ['09 license verification exists', () => expect(pkg.scripts['verify:license']).toBeTruthy()],
  ['10 action pin verification exists', () => expect(pkg.scripts['verify:actions']).toBeTruthy()],
  ['11 React is present', () => expect(pkg.dependencies.react).toBeTruthy()],
  ['12 Supabase JS is present', () => expect(pkg.dependencies['@supabase/supabase-js']).toBeTruthy()],
  ['13 Supabase SSR is present', () => expect(pkg.dependencies['@supabase/ssr']).toBeTruthy()],
  ['14 Stripe is present', () => expect(pkg.dependencies.stripe).toBeTruthy()],
  ['15 Redis client is present', () => expect(pkg.dependencies.ioredis).toBeTruthy()],
  ['16 Helmet is present', () => expect(pkg.dependencies.helmet).toBeTruthy()],
  ['17 rate limiting library is present', () => expect(pkg.dependencies['express-rate-limit']).toBeTruthy()],
  ['18 Zod validation library is present', () => expect(pkg.dependencies.zod).toBeTruthy()],
  ['19 DOMPurify is present', () => expect(pkg.dependencies.dompurify).toBeTruthy()],
  ['20 TypeScript is present in dev dependencies', () => expect(pkg.devDependencies.typescript).toBeTruthy()],
  ['21 legacy Firebase package is absent', () => expect(JSON.stringify(pkg)).not.toMatch(/firebase/i)],
  ['22 package has no firebase-admin dependency', () => expect(pkg.dependencies['firebase-admin']).toBeUndefined()],
  ['23 package has no firebase dependency', () => expect(pkg.dependencies.firebase).toBeUndefined()],
  ['24 package has no google-cloud auth package', () => expect(JSON.stringify(pkg.dependencies)).not.toMatch(/google-auth-library/i)],
  ['25 brace-expansion override is present', () => expect(pkg.overrides['brace-expansion']).toBeTruthy()],
  ['26 minimatch override is present', () => expect(pkg.overrides.minimatch).toBeTruthy()],
  ['27 uuid override is present', () => expect(pkg.overrides.uuid).toBeTruthy()],
  ['28 recast override is present', () => expect(pkg.overrides.recast).toBeTruthy()],
  ['29 package declares proprietary license', () => expect(pkg.license).toContain('Proprietary')],
  ['30 package version is nonzero', () => expect(pkg.version).not.toBe('0.0.0')],
  ['31 CI runs on main pushes', () => expect(ci).toContain('branches: [main]')],
  ['32 CI runs on pull requests', () => expect(ci).toContain('pull_request:')],
  ['33 CI has read-only contents permission', () => expect(ci).toContain('contents: read')],
  ['34 CI uses Ubuntu', () => expect(ci).toContain('runs-on: ubuntu-latest')],
  ['35 CI has a finite timeout', () => expect(ci).toContain('timeout-minutes: 15')],
  ['36 checkout action is pinned by SHA', () => expect(ci).toMatch(/actions\\/checkout@[0-9a-f]{40}/)],
  ['37 setup-node action is pinned by SHA', () => expect(ci).toMatch(/actions\\/setup-node@[0-9a-f]{40}/)],
  ['38 Node 22 is used in CI', () => expect(ci).toContain('node-version: 22')],
  ['39 npm cache is enabled', () => expect(ci).toContain('cache: npm')],
  ['40 CI uses npm ci', () => expect(ci).toContain('npm ci')],
  ['41 CI disables install scripts', () => expect(ci).toContain('--ignore-scripts')],
  ['42 CI disables npm audit during install', () => expect(ci).toContain('--no-audit')],
  ['43 CI disables npm fund noise', () => expect(ci).toContain('--no-fund')],
  ['44 CI verifies license manifest', () => expect(ci).toContain('npm run verify:license')],
  ['45 CI verifies pinned actions', () => expect(ci).toContain('npm run verify:actions')],
  ['46 CI checks lockfile cleanliness', () => expect(ci).toContain('git diff --exit-code -- package-lock.json')],
  ['47 CI typechecks', () => expect(ci).toContain('npm run typecheck')],
  ['48 CI runs tests', () => expect(ci).toContain('npm test')],
  ['49 CI builds production', () => expect(ci).toContain('npm run build')],
  ['50 CI has a verify job', () => expect(ci).toContain('verify:')],
  ['51 worker bounds poll interval', () => expect(worker).toContain('Math.max(250')],
  ['52 worker bounds concurrency minimum', () => expect(worker).toContain('Math.max(1')],
  ['53 worker bounds concurrency maximum', () => expect(worker).toContain('Math.min(50')],
  ['54 worker bounds lead sweep frequency', () => expect(worker).toContain('Math.max(60_000')],
  ['55 worker bounds follow-up frequency', () => expect(worker).toContain('Math.max(60_000')],
  ['56 worker bounds discovery frequency', () => expect(worker).toContain('Math.max(300_000')],
  ['57 worker identifies each process', () => expect(worker).toContain('os.hostname()')],
  ['58 worker identifies process id', () => expect(worker).toContain('process.pid')],
  ['59 worker creates a worker pool', () => expect(worker).toContain('createWorkerPool()')],
  ['60 worker closes its pool in finally', () => expect(worker).toContain('finally{await pool.end();}')],
  ['61 worker sets tenant context in campaign controls', () => expect(worker).toContain("set_config('app.tenant_id',$1,true)")],
  ['62 campaign controls filter by tenant', () => expect(worker).toContain('WHERE tenant_id=$1')],
  ['63 campaign controls use a transaction', () => expect(worker).toContain("await client.query('BEGIN')")],
  ['64 campaign controls commit', () => expect(worker).toContain("await client.query('COMMIT')")],
  ['65 campaign controls rollback on failure', () => expect(worker).toContain("await client.query('ROLLBACK')")],
  ['66 job claim uses row locking', () => expect(worker).toContain('FOR UPDATE SKIP LOCKED')],
  ['67 claimed jobs become running', () => expect(worker).toContain("status='running'")],
  ['68 job attempts increment', () => expect(worker).toContain('Number(job.attempts)+1')],
  ['69 job lock owner is recorded', () => expect(worker).toContain('locked_by=$3')],
  ['70 job lock timestamp is recorded', () => expect(worker).toContain('locked_at=CURRENT_TIMESTAMP')],
  ['71 succeeded jobs clear last error', () => expect(worker).toContain('last_error=NULL')],
  ['72 succeeded jobs release lock', () => expect(worker).toContain('locked_at=NULL,locked_by=NULL')],
  ['73 failed jobs retain error text', () => expect(worker).toContain('last_error=$4')],
  ['74 errors are truncated', () => expect(worker).toContain('message.slice(0,2000)')],
  ['75 exhausted jobs dead-letter', () => expect(worker).toContain("'dead_letter'")],
  ['76 retry jobs return to queue', () => expect(worker).toContain("'queued'")],
  ['77 retries use calculated backoff', () => expect(worker).toContain('calculateBackoff(job.attempts)')],
  ['78 job status updates require running state', () => expect(worker).toContain("WHERE id=$1 AND status='running'")],
  ['79 unknown job kinds fail closed', () => expect(worker).toContain('DISTRIBUTION_UNKNOWN_JOB_KIND')],
  ['80 malformed required URL input fails', () => expect(worker).toContain('DISTRIBUTION_URL_REQUIRED')],
  ['81 outreach requires autonomous gate', () => expect(worker).toContain('autonomousOutreachEnabled()')],
  ['82 outreach checks DB campaign control', () => expect(worker).toContain('outreachEnabled')],
  ['83 paused outreach raises explicit error', () => expect(worker).toContain('DISTRIBUTION_OUTREACH_PAUSED')],
  ['84 follow-ups are gated', () => expect(worker).toContain('followup_outreach')],
  ['85 duplicate initial sends are excluded', () => expect(worker).toContain("m.kind='initial'")],
  ['86 only unsent contacts are selected', () => expect(worker).toContain("m.status='sent'")],
  ['87 contact selection is tenant-scoped', () => expect(worker).toContain('distribution_contacts.id')],
  ['88 contact query has a hard limit', () => expect(worker).toContain('LIMIT 25')],
  ['89 lead sweep has a hard limit', () => expect(worker).toContain('LIMIT 100')],
  ['90 lead qualification jobs are deduplicated', () => expect(worker).toContain("j.kind='qualify_lead'")],
  ['91 discovery requires explicit autonomous flag', () => expect(worker).toContain("DISTRIBUTION_AUTONOMOUS_DISCOVERY==='true'")],
  ['92 discovery obeys DB enablement', () => expect(worker).toContain('controls.discoveryEnabled')],
  ['93 discovery provider only permits HTTP(S)', () => expect(worker).toContain("['http:','https:'].includes(parsed.protocol)")],
  ['94 discovery provider disables automatic redirects', () => expect(worker).toContain("redirect:'manual'")],
  ['95 discovery requests have timeouts', () => expect(worker).toContain('setTimeout(()=>controller.abort(),8000)')],
  ['96 GitHub discovery result URLs are protocol checked', () => expect(worker).toContain("['http:','https:'].includes(url.protocol)")],
  ['97 GitHub discovery has a bounded page size', () => expect(worker).toContain('per_page')],
  ['98 GitHub discovery has a bounded query length', () => expect(worker).toContain('query.trim().slice(0,200)')],
  ['99 Slack alerts have bounded message size', () => expect(worker).toContain('message.slice(0,3_000)')],
  ['100 Slack alerts have a timeout and do not crash worker', () => { expect(worker).toContain('setTimeout(() => controller.abort(), 5_000)'); expect(worker).toContain("catch(error){console.error('[Distribution] Slack alert failed:"); }],
];

describe('SPR 100-point hardening contract', () => {
  it.each(checks)('%s', (_name, check) => { check(); });
  it('contains exactly 100 checks', () => expect(checks).toHaveLength(100));
});
