/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import LegalPageLayout from './LegalPageLayout';

export default function PrivacyPolicyView() {
  return (
    <LegalPageLayout title="Privacy Policy" lastUpdated="September 2, 2026">
      <p>This Privacy Policy describes how <strong>Software Passport Registry Ltd.</strong> ("SPR", "we", "us", or "our") handles information in connection with the Software Passport Registry service (the "Service").</p>
      <p>SPR is an independent software trust and evidence platform. SPR is not a government passport service, government registry, certification authority, or government-affiliated system.</p>
      <p>SPR does not represent that this Policy creates a certification or legal determination of compliance with any particular privacy law. Where a jurisdiction grants additional privacy rights, those rights remain applicable to the extent required by law.</p>
      <section><h2>1. Information We Collect</h2><p><strong>Account information.</strong> When you or your organization create an account, we collect information such as name, email address, company name, and role.</p><p><strong>Software, repository, and evidence information.</strong> The Service is designed around software inventory and evidence: information you or your organization submits about software assets, clients, software bills of materials, vulnerability scan results, repository metadata, and provenance/attestation statements. Where you connect a third-party source, we collect the data that integration provides in order to generate evidence and trust outputs.</p><p><strong>Technical and log information.</strong> We automatically collect certain technical information needed to operate and secure the Service, including IP address, browser/user-agent information, request timestamps, and records of actions taken in your workspace.</p></section>
      <section><h2>2. Cookies and Local Storage</h2><p>The Service does not set third-party advertising or tracking cookies. Authentication is managed by Firebase Authentication. The Service uses browser local storage for limited interface preferences on your device; these preferences are not used by SPR to track you across unrelated websites.</p></section>
      <section><h2>3. How We Use Information</h2><ul><li>To provide, maintain, and secure the Service, including generating evidence-based trust outputs and reports.</li><li>To authenticate users and enforce access controls and workspace/client data isolation.</li><li>To process billing and manage subscriptions when billing features are enabled.</li><li>To detect, investigate, and prevent misuse, security incidents, or violations of our Terms of Service.</li><li>To communicate with you about your account or the Service.</li></ul></section>
      <section><h2>4. Third-Party Service Providers</h2><p>We use third-party providers to operate parts of the Service. We do not sell personal information to these providers.</p><ul><li><strong>Authentication:</strong> Firebase Authentication (Google), for sign-in and session security.</li><li><strong>Billing:</strong> Stripe, when enabled, to process subscription payments. SPR does not itself store full payment card numbers.</li><li><strong>Hosting and infrastructure:</strong> Railway for the application backend/database and Vercel for web delivery.</li><li><strong>Optional AI assistance:</strong> where enabled, selected content may be sent to Google's Gemini API to generate plain-language summaries, and to OpenAI (via the Vercel AI Gateway) to generate plain-English explanations of trust findings. AI output is assistive and is not itself an independent evidentiary source.</li><li><strong>Optional error monitoring:</strong> Sentry, where configured, to capture application error information.</li><li><strong>Optional integrations:</strong> source-code hosting and MSP operations providers that you explicitly connect and authorize.</li></ul></section>
      <section><h2>5. Data Retention</h2><p>We retain account and workspace information for as long as reasonably necessary to provide the Service and for legitimate business, security, dispute-resolution, and legal purposes. We do not claim a fixed deletion period for every data category because retention can vary by account configuration, evidence type, legal obligation, and third-party processing requirements.</p></section>
      <section><h2>6. Security Measures</h2><p>We use layered technical and organizational safeguards appropriate to the Service, including HTTPS/TLS, authentication and authorization controls, workspace/client scoping, encrypted handling of integration credentials, audit logging, input validation, and rate limiting on sensitive endpoints. No security measure can guarantee absolute security.</p></section>
      <section><h2>7. Data Sharing</h2><p>We do not sell personal information. We share information only with service providers needed to operate the Service, with authorized members of your organization's workspace, when required by law or legal process, to protect rights or safety, or in connection with a corporate transaction where applicable protections continue.</p></section>
      <section><h2>8. Your Rights and How to Contact Us</h2><p>Depending on your jurisdiction, you may have rights to access, correct, delete, restrict, or object to certain processing of personal information. Privacy requests and questions may be sent to <strong>contact@softwarepassportregistry.com</strong>.</p></section>
      <section><h2>9. International Data Handling</h2><p>Our service providers may process information in countries other than your own. Where applicable law requires safeguards for cross-border processing, SPR will use appropriate mechanisms or otherwise process information as permitted by law.</p></section>
      <section><h2>10. Children's Privacy</h2><p>The Service is intended for business use and is not directed to children. We do not knowingly collect personal information from children under 16 through the Service.</p></section>
      <section><h2>11. Changes to This Policy</h2><p>We may update this Privacy Policy from time to time. Material changes will be reflected by updating the date above and, where appropriate, providing additional notice.</p></section>
      <section><h2>12. Contact</h2><p>Privacy questions and requests: <strong>Software Passport Registry Ltd.</strong>, <strong>contact@softwarepassportregistry.com</strong>.</p></section>
    </LegalPageLayout>
  );
}
