/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import LegalPageLayout from './LegalPageLayout';

export default function TermsView() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="September 2, 2026">
      <p>These Terms of Service ("Terms") govern access to and use of the Service operated by <strong>Software Passport Registry Ltd.</strong> ("SPR", "we", "us", or "our").</p>
      <p>SPR is an independent software trust and evidence platform. SPR is not a government passport service, government registry, certification authority, or government-affiliated system.</p>
      <p>These Terms describe the Service and its limitations. They are not a security certification, legal opinion, or guarantee of future software behavior.</p>
      <section><h2>1. Acceptance</h2><p>By creating an account, accessing, or using the Service, you agree to these Terms. If you use the Service for an organization, you represent that you have authority to do so.</p></section>
      <section><h2>2. Service Description</h2><p>SPR is a software evidence-and-trust platform. It helps users inventory software, collect and organize evidence such as SBOMs, vulnerability results, repository signals and provenance information, and present evidence as trust states, reports and dashboards.</p><p><strong>SPR does not certify, warrant, guarantee, or attest that software, a vendor, or an organization is secure, compliant, or free of vulnerabilities.</strong> A trust state or "Verified" label reflects evidence available to SPR at the time it was computed and is not an independent security audit, legal opinion, or formal certification.</p></section>
      <section><h2>3. Accounts and Responsibilities</h2><ul><li>Keep account credentials confidential and provide accurate account information.</li><li>Maintain appropriate roles and access for workspace members.</li><li>Submit only software, evidence, attestations, and other content you are authorized to submit.</li><li>Remain responsible for the accuracy of submitted information and for your own procurement, security, and regulatory decisions.</li></ul></section>
      <section><h2>4. Acceptable Use</h2><p>You must not submit knowingly false or materially misleading evidence; access another tenant's data without authorization; probe or test SPR security controls without written authorization; violate law or third-party rights; or interfere with Service availability or integrity.</p></section>
      <section><h2>5. Customer Data</h2><p>You retain ownership of content you submit. You grant SPR the limited rights needed to host, process, analyze, and display that content to provide the Service. SPR may independently verify selected evidence types where the product documents that verification step. Verification of one property does not imply verification of every related property.</p></section>
      <section><h2>6. Intellectual Property</h2><p>SPR and its licensors retain rights in the Service, software, design, and underlying technology, excluding Customer Data. Subject to these Terms, SPR grants you a limited, non-exclusive right to use the Service for authorized business purposes.</p></section>
      <section><h2>7. Third-Party Services</h2><p>The Service depends on third-party providers for portions of hosting, authentication, billing, source-code integrations, vulnerability data, optional AI assistance, monitoring, and related infrastructure. Third-party services are subject to their own terms and availability.</p></section>
      <section><h2>8. Availability and Changes</h2><p>We aim to operate the Service reliably but do not guarantee uninterrupted or error-free operation. Features may change, be suspended, or be discontinued.</p></section>
      <section><h2>9. Disclaimers</h2><p><strong>THE SERVICE, INCLUDING TRUST STATES, EVIDENCE SUMMARIES, REPORTS, AND OTHER OUTPUT, IS PROVIDED FOR INFORMATIONAL AND DUE-DILIGENCE PURPOSES ONLY. IT IS NOT LEGAL, FINANCIAL, CYBERSECURITY, COMPLIANCE, OR OTHER PROFESSIONAL ADVICE, AND IT IS NOT A SUBSTITUTE FOR AN INDEPENDENT SECURITY AUDIT OR FORMAL CERTIFICATION.</strong></p><p>Except where a separate written agreement expressly provides otherwise, the Service is provided on an "as is" and "as available" basis to the maximum extent permitted by applicable law.</p></section>
      <section><h2>10. Limitation of Liability</h2><p>To the maximum extent permitted by applicable law, SPR and its officers, employees, and agents will not be liable for indirect, incidental, special, consequential, or punitive damages, or loss of profits, revenue, data, or business opportunity arising from use of the Service. To the extent a limitation is permitted by applicable law, aggregate liability arising from the Service will not exceed amounts paid to SPR for the Service during the twelve months preceding the event giving rise to the claim.</p></section>
      <section><h2>11. Indemnification</h2><p>You agree to indemnify and hold SPR harmless from claims and reasonable expenses arising from your unlawful use of the Service, your Customer Data, or your violation of these Terms or third-party rights, to the extent permitted by applicable law.</p></section>
      <section><h2>12. Termination</h2><p>You may stop using the Service at any time. SPR may suspend or terminate access for material breach, security reasons, or legal requirements. Provisions that by their nature should survive termination will survive.</p></section>
      <section><h2>13. Governing Law</h2><p>These Terms are governed by the laws of the Province of British Columbia and the federal laws of Canada applicable therein, without regard to conflict-of-laws principles. Subject to any separate written agreement between the parties, the parties submit to the exclusive jurisdiction of the courts located in British Columbia, Canada for any dispute arising from these Terms or the Service.</p></section>
      <section><h2>14. Privacy</h2><p>Our handling of personal information is described in the <a href="/privacy">Privacy Policy</a>.</p></section>
      <section><h2>15. Changes</h2><p>We may update these Terms from time to time. Material changes will be reflected by an updated date and, where appropriate, additional notice.</p></section>
      <section><h2>16. Contact</h2><p>Questions about these Terms can be directed to <strong>Software Passport Registry Ltd.</strong> at <strong>contact@softwarepassportregistry.com</strong>.</p></section>
    </LegalPageLayout>
  );
}
