import { ControlObservation } from '../trust/trust-loop.ts';
import { Provider, ProviderCredentials } from './adapters.ts';

const TIMEOUT=15000,MAX=2_000_000;
async function getJson(url:string,headers:Record<string,string>):Promise<{body:any;status:number}>{const c=new AbortController();const t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{headers:{accept:'application/json',...headers},signal:c.signal});const text=await r.text();if(Buffer.byteLength(text)>MAX)throw new Error('PROVIDER_RESPONSE_TOO_LARGE');let body:any;try{body=JSON.parse(text);}catch{body={text:text.slice(0,MAX)}}if(!r.ok)throw new Error(`PROVIDER_HTTP_${r.status}`);return{body,status:r.status};}finally{clearTimeout(t);}}
function bearer(c:ProviderCredentials):Record<string,string>{if(!c.accessToken)throw new Error('CREDENTIAL_MISSING_ACCESS_TOKEN');return{Authorization:`Bearer ${c.accessToken}`};}
function basic(c:ProviderCredentials):Record<string,string>{if(!c.email||!c.apiToken)throw new Error('CREDENTIAL_MISSING_EMAIL_OR_TOKEN');return{Authorization:`Basic ${Buffer.from(`${c.email}:${c.apiToken}`).toString('base64')}`};}
function obs(provider:string,controlId:string,title:string,severity:any,subject:string,url:string,body:any,status:'PASS'|'FAIL'|'UNKNOWN',method:string,limitation?:string):ControlObservation{return{provider,controlId,title,severity,subject,sourceUrl:url,observedAt:new Date().toISOString(),verificationMethod:method,value:body,status,limitation};}
async function probe(provider:string,controlId:string,title:string,severity:any,subject:string,url:string,headers:Record<string,string>,evaluate:(body:any)=>'PASS'|'FAIL'|'UNKNOWN',method:string,limitation?:string):Promise<ControlObservation>{try{const r=await getJson(url,headers);const status=evaluate(r.body);return obs(provider,controlId,title,severity,subject,url,r.body,status,method,limitation||(status==='UNKNOWN'?'Provider response did not expose enough authoritative data to determine the control.':undefined));}catch(e:any){return obs(provider,controlId,title,severity,subject,url,{error:e?.message||'PROBE_FAILED'},'UNKNOWN',method,'Collection failed; no pass/fail conclusion was inferred.');}}
export async function collectDeepProviderEvidence(provider:Provider,c:ProviderCredentials):Promise<ControlObservation[]>{const out:ControlObservation[]=[];const add=async(controlId:string,title:string,severity:any,subject:string,url:string,headers:Record<string,string>,evaluate:(body:any)=>'PASS'|'FAIL'|'UNKNOWN',method:string,limitation?:string)=>out.push(await probe(provider,controlId,title,severity,subject,url,headers,evaluate,method,limitation));
if(provider==='microsoft-365'){const h=bearer(c),base='https://graph.microsoft.com/v1.0';await add('m365-global-admin-inventory','Global administrator inventory','high','tenant',`${base}/directoryRoles?$filter=displayName%20eq%20%27Global%20Administrator%27&$expand=members`,h,b=>Array.isArray(b?.value)?(b.value.length>0?'PASS':'UNKNOWN'):'UNKNOWN','Microsoft Graph directory role and member collection');await add('m365-user-mfa-signal','User authentication methods exposure','high','tenant',`${base}/users?$select=id,displayName,userPrincipalName,accountEnabled&$top=100`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Microsoft Graph user inventory collection');await add('m365-conditional-access','Conditional access policy inventory','high','tenant',`${base}/identity/conditionalAccess/policies?$top=100`,h,b=>Array.isArray(b?.value)?(b.value.length?'PASS':'FAIL'):'UNKNOWN','Microsoft Graph conditional-access policy collection');
  // Microsoft Defender / security posture evidence, via Microsoft Graph's
  // Security API (the same OAuth app registration, provided it has been
  // granted SecurityEvents.Read.All -- a real, documented Graph API surface
  // covering Defender for Endpoint/Office/Identity/Cloud Apps alerts
  // uniformly, not a separate "Defender connector"). If the token lacks
  // that scope the probe fails closed to UNKNOWN via probe()'s catch, it
  // never infers a clean security posture from a permissions error.
  await add('m365-security-alerts','Microsoft Defender / Graph Security open alerts','high','tenant',`${base}/security/alerts_v2?$top=100`,h,b=>Array.isArray(b?.value)?(b.value.length?'FAIL':'PASS'):'UNKNOWN','Microsoft Graph Security alerts_v2 collection (Defender for Endpoint/Office/Identity/Cloud Apps)');
  await add('m365-secure-score','Microsoft Secure Score evidence availability','medium','tenant',`${base}/security/secureScores?$top=1`,h,b=>Array.isArray(b?.value)&&b.value.length?'PASS':'UNKNOWN','Microsoft Graph Security secureScores collection','A numeric score alone does not establish pass/fail; this confirms secure-score evidence was collected for the trust engine to weigh, not that the tenant\'s posture is good or bad.');
  await add('m365-secure-score-recommendations','Microsoft Secure Score recommended actions inventory','medium','tenant',`${base}/security/secureScoreControlProfiles?$top=100`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Microsoft Graph Security secureScoreControlProfiles collection');
  return out;}
if(provider==='aws'){const region=c.region||'us-east-1',base='https://iam.amazonaws.com';out.push(obs(provider,'aws-credentials-present','AWS IAM control collection requires signed IAM calls','high','account',base,{},'UNKNOWN','AWS IAM control collection','Existing credentials are valid only for the STS identity probe; IAM control calls require provider-specific signed requests.'));out.push(obs(provider,'aws-region-scope','AWS regional scope explicitly configured','medium','account',base,{region},c.region?'PASS':'UNKNOWN','Configuration evidence'));out.push(obs(provider,'aws-account-identity','AWS account identity available','informational','account',`https://sts.${region}.amazonaws.com`,{region},'UNKNOWN','Delegated to authenticated STS collector','The authoritative STS result is persisted by the base adapter; this deep pack does not duplicate it.'));return out;}
if(provider==='azure'){const h=bearer(c),sub=encodeURIComponent(c.subscriptionId||''),base='https://management.azure.com';await add('azure-resource-groups','Azure resource inventory','medium','subscription',`${base}/subscriptions/${sub}/resourcegroups?api-version=2021-04-01&$top=100`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Azure Resource Manager resource-group collection');await add('azure-security-alerts','Azure security alert inventory','high','subscription',`${base}/subscriptions/${sub}/providers/Microsoft.Security/alerts?api-version=2022-01-01&$top=100`,h,b=>Array.isArray(b?.value)?(b.value.length?'FAIL':'PASS'):'UNKNOWN','Azure Security alerts collection');await add('azure-activity-logging','Azure activity log visibility','high','subscription',`${base}/subscriptions/${sub}/providers/microsoft.insights/eventtypes/management/values?api-version=2015-04-01&$top=1`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Azure Monitor activity-log collection');return out;}
if(provider==='google-cloud'){const h=bearer(c),base='https://cloudresourcemanager.googleapis.com/v3';await add('gcp-project-inventory','GCP project inventory','medium','organization',`${base}/projects?pageSize=100`,h,b=>Array.isArray(b?.projects)?'PASS':'UNKNOWN','Google Cloud Resource Manager project collection');await add('gcp-service-account-inventory','GCP service-account inventory','high','projects',`https://iam.googleapis.com/v1/projects/${encodeURIComponent(c.projectId||'')}/serviceAccounts?pageSize=100`,h,b=>Array.isArray(b?.accounts)?'PASS':'UNKNOWN','Google IAM service-account collection');await add('gcp-iam-policy','GCP IAM policy visibility','high','project',`https://cloudresourcemanager.googleapis.com/v3/projects/${encodeURIComponent(c.projectId||'')}:getIamPolicy`,h,b=>b?.bindings?'PASS':'UNKNOWN','Google Cloud Resource Manager IAM policy collection');return out;}
if(provider==='gitlab'){const base=(c.baseUrl||'https://gitlab.com').replace(/\/$/,''),h=bearer(c);await add('gitlab-project-security','GitLab project/security inventory','high','account',`${base}/api/v4/projects?membership=true&per_page=100&simple=true`,h,b=>Array.isArray(b)?'PASS':'UNKNOWN','GitLab projects API collection');await add('gitlab-ci-config','GitLab CI/CD configuration visibility','medium','account',`${base}/api/v4/projects?membership=true&per_page=100&simple=false`,h,b=>Array.isArray(b)?'PASS':'UNKNOWN','GitLab project configuration collection');await add('gitlab-vulnerability-feed','GitLab vulnerability/reporting inventory','high','account',`${base}/api/v4/vulnerabilities?per_page=100`,h,b=>Array.isArray(b)?(b.length?'FAIL':'PASS'):'UNKNOWN','GitLab vulnerability API collection');return out;}
if(provider==='bitbucket'){const base=(c.baseUrl||'https://api.bitbucket.org/2.0').replace(/\/$/,''),h=bearer(c);await add('bitbucket-repository-inventory','Bitbucket repository inventory','medium','account',`${base}/repositories?role=member&pagelen=100`,h,b=>Array.isArray(b?.values)?'PASS':'UNKNOWN','Bitbucket repository collection');await add('bitbucket-branch-restrictions','Bitbucket branch restriction visibility','high','account',`${base}/repositories?role=member&pagelen=100&fields=values.full_name`,h,b=>Array.isArray(b?.values)?'PASS':'UNKNOWN','Bitbucket repository metadata collection','Restriction details require per-repository calls; this observation is visibility only.');await add('bitbucket-pipeline-inventory','Bitbucket pipeline posture visibility','medium','account',`${base}/repositories?role=member&pagelen=100&fields=values.full_name,values.mainbranch`,h,b=>Array.isArray(b?.values)?'PASS':'UNKNOWN','Bitbucket repository/pipeline inventory collection');return out;}
if(provider==='azure-devops'){const o=c.organization,h={Authorization:`Basic ${Buffer.from(`:${c.accessToken||''}`).toString('base64')}`},base=`https://dev.azure.com/${encodeURIComponent(o||'')}`;await add('azuredevops-project-inventory','Azure DevOps project inventory','medium','organization',`${base}/_apis/projects?api-version=7.1&$top=100`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Azure DevOps project collection');await add('azuredevops-build-security','Azure DevOps build/pipeline inventory','high','organization',`${base}/_apis/build/builds?api-version=7.1&$top=100`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Azure DevOps build inventory');await add('azuredevops-repo-security','Azure DevOps repository inventory','high','organization',`${base}/_apis/git/repositories?api-version=7.1&$top=100`,h,b=>Array.isArray(b?.value)?'PASS':'UNKNOWN','Azure DevOps Git repository collection');return out;}
if(provider==='jira'){const base=(c.baseUrl||'').replace(/\/$/,''),h=basic(c);await add('jira-project-inventory','Jira project inventory','medium','site',`${base}/rest/api/3/project/search?maxResults=100`,h,b=>Array.isArray(b?.values)?'PASS':'UNKNOWN','Jira REST project collection');await add('jira-security-admin','Jira security/admin posture visibility','high','site',`${base}/rest/api/3/configuration`,h,b=>b&&typeof b==='object'?'PASS':'UNKNOWN','Jira REST configuration collection');await add('jira-open-remediation','Jira open remediation workload','medium','site',`${base}/rest/api/3/search?jql=${encodeURIComponent('statusCategory != Done ORDER BY priority DESC')}&maxResults=100`,h,b=>Array.isArray(b?.issues)?(b.issues.length?'FAIL':'PASS'):'UNKNOWN','Jira REST issue search for open work');return out;}
if(provider==='confluence'){const base=(c.baseUrl||'').replace(/\/$/,''),h=basic(c);await add('confluence-space-inventory','Confluence space inventory','medium','site',`${base}/wiki/rest/api/space?limit=100`,h,b=>Array.isArray(b?.results)?'PASS':'UNKNOWN','Confluence REST space collection');await add('confluence-user-inventory','Confluence current-user identity','medium','site',`${base}/wiki/rest/api/user/current`,h,b=>b?.accountId?'PASS':'UNKNOWN','Confluence REST current-user collection');await add('confluence-content-inventory','Confluence content inventory','low','site',`${base}/wiki/rest/api/content?limit=1`,h,b=>Array.isArray(b?.results)?'PASS':'UNKNOWN','Confluence REST content collection');return out;}
if(provider==='slack'){const h=bearer(c),base='https://slack.com/api';await add('slack-authenticated-workspace','Slack workspace identity','informational','workspace',`${base}/auth.test`,h,b=>b?.ok===true?'PASS':'UNKNOWN','Slack auth.test');await add('slack-team-profile','Slack workspace profile','medium','workspace',`${base}/team.info`,h,b=>b?.ok===true?'PASS':'UNKNOWN','Slack team.info');await add('slack-user-inventory','Slack user inventory','medium','workspace',`${base}/users.list?limit=200`,h,b=>b?.ok===true?'PASS':'UNKNOWN','Slack users.list');return out;}
if(provider==='connectwise'){const base=(c.baseUrl||'').replace(/\/$/,''),auth=Buffer.from(`${c.companyId||''}+${c.publicKey||''}:${c.privateKey||''}`).toString('base64'),h={Authorization:`Basic ${auth}`};await add('connectwise-company-inventory','ConnectWise company inventory','medium','tenant',`${base}/v4_6_release/apis/3.0/company/companies?pageSize=100`,h,b=>Array.isArray(b)?'PASS':'UNKNOWN','ConnectWise company API');await add('connectwise-ticket-inventory','ConnectWise service-ticket workload','medium','tenant',`${base}/v4_6_release/apis/3.0/service/tickets?pageSize=100&conditions=${encodeURIComponent('closedFlag=false')}`,h,b=>Array.isArray(b)?(b.length?'FAIL':'PASS'):'UNKNOWN','ConnectWise service-ticket API');await add('connectwise-member-inventory','ConnectWise privileged/member inventory','high','tenant',`${base}/v4_6_release/apis/3.0/system/members?pageSize=100`,h,b=>Array.isArray(b)?'PASS':'UNKNOWN','ConnectWise member API');return out;}
if(provider==='autotask'){const base=(c.baseUrl||'').replace(/\/$/,'');const h={ApiIntegrationCode:c.integrationCode||'',UserName:c.username||'',Secret:c.secret||'','Content-Type':'application/json'};await add('autotask-company-inventory','Autotask company inventory','medium','tenant',`${base}/v1.0/Companies/query`,h,b=>Array.isArray(b?.items)?'PASS':'UNKNOWN','Autotask company API');await add('autotask-open-ticket-workload','Autotask open-ticket workload','medium','tenant',`${base}/v1.0/Tickets/query`,h,b=>Array.isArray(b?.items)?(b.items.length?'FAIL':'PASS'):'UNKNOWN','Autotask ticket API');await add('autotask-resource-inventory','Autotask resource inventory','high','tenant',`${base}/v1.0/Resources/query`,h,b=>Array.isArray(b?.items)?'PASS':'UNKNOWN','Autotask resource API');return out;}
if(provider==='ninjaone'){const base=(c.baseUrl||'https://app.ninjarmm.com').replace(/\/$/,''),h=bearer(c);await add('ninja-device-inventory','NinjaOne endpoint inventory','medium','tenant',`${base}/api/v2/devices?pageSize=100`,h,b=>Array.isArray(b)?'PASS':'UNKNOWN','NinjaOne device API');await add('ninja-alert-inventory','NinjaOne endpoint/security alert inventory','high','tenant',`${base}/api/v2/alerts?pageSize=100`,h,b=>Array.isArray(b)?(b.length?'FAIL':'PASS'):'UNKNOWN','NinjaOne alert API');await add('ninja-patch-inventory','NinjaOne patch posture inventory','high','tenant',`${base}/api/v2/patches?pageSize=100`,h,b=>Array.isArray(b)?(b.length?'FAIL':'PASS'):'UNKNOWN','NinjaOne patch API');return out;}
if(provider==='hudu'){const base=(c.baseUrl||'').replace(/\/$/,''),h={'x-api-key':c.apiKey||''};await add('hudu-company-inventory','Hudu company inventory','medium','tenant',`${base}/api/v1/companies?page_size=100`,h,b=>Array.isArray(b?.companies)||Array.isArray(b)?'PASS':'UNKNOWN','Hudu companies API');await add('hudu-asset-inventory','Hudu asset inventory','medium','tenant',`${base}/api/v1/assets?page_size=100`,h,b=>Array.isArray(b?.assets)||Array.isArray(b)?'PASS':'UNKNOWN','Hudu assets API');await add('hudu-password-policy-visibility','Hudu credential/policy inventory','high','tenant',`${base}/api/v1/companies?page_size=1`,h,b=>b?'PASS':'UNKNOWN','Hudu company API','Credential-policy state is not inferred without an authoritative policy endpoint.');return out;}
return out;}
