import crypto from 'node:crypto';
import { Pool } from 'pg';
import { collectDeepProviderEvidence } from '../integrations/deep-collectors.ts';
import { collectGitHubDeepEvidence } from '../integrations/github-deep.ts';
import { decryptCredentials } from '../integrations/credential-vault.ts';
import { persistTrustLoop, ControlObservation } from '../trust/trust-loop.ts';
import { safeNetworkFetch } from '../utils/monitoring.ts';

const PROVIDERS=new Set(['github','gitlab','bitbucket','azure-devops','jira','confluence','slack','microsoft-365','aws','azure','google-cloud','connectwise','autotask','ninjaone','hudu']);
function id(p:string){return`${p}_${crypto.randomUUID().replaceAll('-','')}`;}
function pool(){return new Pool(process.env.DATABASE_URL?{connectionString:process.env.DATABASE_URL}:{host:process.env.SQL_HOST,user:process.env.SQL_USER,password:process.env.SQL_PASSWORD,database:process.env.SQL_DB_NAME});}
async function claim(p:Pool){const c=await p.connect();try{await c.query('BEGIN');const r=await c.query(`WITH candidate AS (SELECT id FROM collector_jobs WHERE state IN ('queued','failed') AND next_attempt_at::timestamptz <= CURRENT_TIMESTAMP AND attempt_number < maximum_attempts ORDER BY created_at::timestamptz FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE collector_jobs j SET state='running',lease_owner=$1,lease_expires_at=(CURRENT_TIMESTAMP+INTERVAL '5 minutes')::text,heartbeat_at=CURRENT_TIMESTAMP::text,started_at=COALESCE(started_at,CURRENT_TIMESTAMP::text),attempt_number=attempt_number+1 FROM candidate WHERE j.id=candidate.id RETURNING j.*`,[process.pid.toString()]);await c.query('COMMIT');return r.rows[0]||null;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
async function credentials(p:Pool,job:any){if(!job.monitoring_configuration_id)return{};const r=await p.query(`SELECT credential_reference_id FROM monitoring_configurations WHERE id=$1 AND tenant_id=$2 LIMIT 1`,[job.monitoring_configuration_id,job.tenant_id]);const ref=r.rows[0]?.credential_reference_id;if(!ref)return{};const x=await p.query(`SELECT encrypted_payload FROM credential_references WHERE id=$1 AND tenant_id=$2 AND state='active' LIMIT 1`,[ref,job.tenant_id]);if(!x.rows[0])throw new Error('CREDENTIAL_REFERENCE_NOT_FOUND');return decryptCredentials(x.rows[0].encrypted_payload) as Record<string,string>;}
async function networkObservation(job:any):Promise<ControlObservation>{const url=job.subject_identifier;try{const r=await safeNetworkFetch(url,{timeoutMs:15000,maxBytes:1048576,maxRedirects:3});return{provider:'network',controlId:job.collector_id,title:`${job.collector_id} endpoint observation`,severity:'medium',subject:url,sourceUrl:r.finalUrl,observedAt:new Date().toISOString(),verificationMethod:`SPR ${job.collector_id} collector`,value:{status:r.response.status,contentType:r.response.headers.get('content-type')||null},status:r.response.ok?'PASS':'FAIL'};}catch(e:any){return{provider:'network',controlId:job.collector_id,title:`${job.collector_id} endpoint observation`,severity:'medium',subject:url,sourceUrl:url,observedAt:new Date().toISOString(),verificationMethod:`SPR ${job.collector_id} collector`,value:{error:e?.message||'NETWORK_COLLECTION_FAILED'},status:'UNKNOWN',limitation:'Network collection failed; SPR does not infer a pass or failure.'};}}
async function execute(p:Pool,job:any){const c=await credentials(p,job);if(PROVIDERS.has(job.collector_id)){const observations=job.collector_id==='github'?await collectGitHubDeepEvidence(c):await collectDeepProviderEvidence(job.collector_id,c);return observations;}if(['tls','domain_dns','uptime'].includes(job.collector_id))return[await networkObservation(job)];if(job.collector_id==='repository'||job.collector_id==='dependency'||job.collector_id==='release'){const token=c.accessToken||c.token;if(!token)throw new Error('CREDENTIAL_MISSING_ACCESS_TOKEN');const repo=job.subject_identifier;const api=`https://api.github.com/repos/${repo}`;const h={accept:'application/vnd.github+json',authorization:`Bearer ${token}`,'x-github-api-version':'2026-03-10'};const r=await fetch(api,{headers:h});if(!r.ok)throw new Error(`GITHUB_HTTP_${r.status}`);const body=await r.json();return[{provider:'github',controlId:job.collector_id,title:`GitHub ${job.collector_id} observation`,severity:'medium',subject:repo,sourceUrl:api,observedAt:new Date().toISOString(),verificationMethod:`GitHub REST ${job.collector_id} collector`,value:body,status:'PASS'} as ControlObservation];}throw new Error('COLLECTOR_UNSUPPORTED');}
async function complete(p:Pool,job:any,observations:ControlObservation[]){const result=await persistTrustLoop({tenantId:job.tenant_id,passportId:job.passport_id,clientId:job.client_id,assetId:job.asset_id,observations});const now=new Date().toISOString();await p.query(`UPDATE collector_jobs SET state='succeeded',safe_error_code=NULL,safe_error_message=NULL,lease_owner=NULL,lease_expires_at=NULL,heartbeat_at=NULL,completed_at=$2 WHERE id=$1`,[job.id,now]);await p.query(`INSERT INTO collector_results (id,tenant_id,client_id,asset_id,passport_id,job_id,collector_id,collector_version,subject_type,subject_identifier,status,started_at,completed_at,evidence_ids,finding_ids,verification_methods,limitations) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'succeeded',$11,$12,$13,$14,$15,$16) ON CONFLICT DO NOTHING`,[id('collector-result'),job.tenant_id,job.client_id,job.asset_id,job.passport_id,job.id,job.collector_id,job.collector_version,job.subject_type,job.subject_identifier,job.started_at,now,JSON.stringify(result.evidenceIds),JSON.stringify(result.findings.map((f:any)=>f.id)),JSON.stringify(observations.map(o=>o.verificationMethod)),JSON.stringify(observations.map(o=>o.limitation).filter(Boolean))]);return result;}
async function fail(p:Pool,job:any,error:any){const now=new Date().toISOString();const terminal=job.attempt_number>=job.maximum_attempts;await p.query(`UPDATE collector_jobs SET state=$2,safe_error_code=$3,safe_error_message=$4,lease_owner=NULL,lease_expires_at=NULL,heartbeat_at=NULL,completed_at=CASE WHEN $2='dead_lettered' THEN $5 ELSE completed_at END,next_attempt_at=($5::timestamptz+make_interval(secs=>LEAST(3600,30*POWER(2,attempt_number))))::text WHERE id=$1`,[job.id,terminal?'dead_lettered':'failed','COLLECTOR_EXECUTION_FAILED',String(error?.message||error).slice(0,500),now]);}
export async function runTrustMonitoringWorkerLoop(){const p=pool();for(;;){const job=await claim(p);if(!job){await new Promise(r=>setTimeout(r,1500));continue;}try{const observations=await execute(p,job);await complete(p,job,observations);}catch(e){await fail(p,job,e);}}}
