/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Public sample Passport — a static, read-only illustration of the artifact.
 *
 * SAFETY PROPERTIES, deliberate and load-bearing:
 *  - It performs NO network or database access. Nothing here can reach a
 *    tenant, a real passport, evidence, credentials or an internal id, so it
 *    cannot become an authorization bypass or a data-exposure path.
 *  - Every value below is fabricated illustration and is labelled as such on
 *    the page itself, repeatedly. It must never be mistaken for an
 *    independently verified production asset.
 *  - The illustrated decision is PARTIAL with an UNKNOWN claim left visible,
 *    because that is what SPR's policy actually produces for a repository
 *    scan today. Showing a glowing VERIFIED here would misrepresent the
 *    product: under policy 1.0.0 nothing reaches VERIFIED without a publisher
 *    attestation.
 *  - It calculates nothing. The states below are literal strings, not a
 *    computed decision — the UI is never an evaluator.
 */

import { DecisionHero, GlassPanel, SectionHeader, DecisionBadge, EvidenceCard, ReasonCode } from './design/CommandCenter';

const SAMPLE_EVIDENCE = [
  { id: 'ev-repo', name: 'Repository source descriptor', type: 'Attestation', source: 'github.com', party: 'third-party' as const, observedAt: '2026-08-29T22:28:51.000Z', hash: 'sha256:47cfc83c69f6116b3682d88a29…' },
  { id: 'ev-sbom', name: 'Syft CycloneDX SBOM summary', type: 'Build Log', source: 'syft', party: 'first-party' as const, observedAt: '2026-08-29T22:28:51.000Z', hash: 'sha256:89072ea24b46500d9e3be617…' },
  { id: 'ev-osv-1', name: 'OSV response for actions/checkout@v4', type: 'Security Scan', source: 'api.osv.dev', party: 'third-party' as const, observedAt: '2026-08-29T22:28:52.000Z', hash: 'sha256:465d448ad887a3c9d9ad15ae…' },
  { id: 'ev-osv-2', name: 'OSV response for actions/setup-node@v4', type: 'Security Scan', source: 'api.osv.dev', party: 'third-party' as const, observedAt: '2026-08-29T22:28:52.000Z', hash: 'sha256:d1dcd4dfe9562e62bf30e059…' },
];

const SAMPLE_CLAIMS = [
  { claim: 'REPOSITORY_IDENTITY', state: 'VERIFIED' as const, note: 'Resolved to an immutable commit SHA observed directly from github.com.' },
  { claim: 'DEPENDENCY_VULNERABILITY_STATE', state: 'VERIFIED' as const, note: 'Queried against api.osv.dev within the freshness window.' },
  { claim: 'DEPENDENCY_INVENTORY', state: 'PARTIAL' as const, note: 'SBOM generated by a first-party tool; no independent corroboration.' },
  { claim: 'SECRET_EXPOSURE_STATE', state: 'PARTIAL' as const, note: 'Scanned by SPR itself. SPR cannot independently verify absence of secrets.' },
  { claim: 'BUILD_PROVENANCE', state: 'UNKNOWN' as const, note: 'No publisher attestation has been supplied for this release.' },
];

function DemoBanner() {
  return (
    <div
      role="note"
      className="rounded-xl border border-[var(--cc-partial)]/45 bg-[color-mix(in_srgb,var(--cc-partial)_10%,transparent)] px-5 py-4"
    >
      <div className="cc-eyebrow" style={{ color: 'var(--cc-partial)' }}>Demo · Sample data</div>
      <p className="mt-2 text-sm leading-6 text-[var(--cc-ink)]">
        This is a <strong>sample Passport for demonstration only</strong>. Every value on this page is
        illustrative. It is not a real assessment, not an independently verified asset, and makes no
        claim about any actual software. To see a real result, run a Free Review on a public repository.
      </p>
    </div>
  );
}

export default function DemoPassport({ onRunFreeReview, onHome }: { onRunFreeReview: () => void; onHome: () => void }) {
  return (
    <div className="cc-canvas min-h-screen px-6 py-10 text-[var(--cc-ink)]">
      <div className="mx-auto max-w-5xl space-y-6">
        <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-xs text-[var(--cc-ink-faint)]">
          <button onClick={onHome} className="hover:text-[var(--cc-investigate)]">Software Passport Registry</button>
          <span aria-hidden="true">/</span>
          <span className="text-[var(--cc-ink-muted)]">Sample Passport</span>
        </nav>

        <DemoBanner />

        <header>
          <div className="cc-eyebrow">01 · Software identity</div>
          <h1 className="mt-1 text-2xl font-bold">example-org / sample-service <span className="text-[var(--cc-ink-faint)]">(sample)</span></h1>
          <dl className="mt-3 grid grid-cols-2 gap-x-6 gap-y-1.5 text-xs sm:grid-cols-4">
            {[
              ['Publisher', 'example-org (sample)'],
              ['Commit', 'df476048…0ca2b25a (sample)'],
              ['Source', 'github.com'],
              ['Last observed', '29 Aug 2026 (sample)'],
            ].map(([term, value]) => (
              <div key={term}>
                <dt className="text-[10px] uppercase tracking-wide text-[var(--cc-ink-faint)]">{term}</dt>
                <dd className="text-[var(--cc-ink)]">{value}</dd>
              </div>
            ))}
          </dl>
        </header>

        {/* Literal illustrative values - nothing here is computed. */}
        <DecisionHero
          state="PARTIAL"
          explanation="Decision: PARTIAL under policy 1.0.0. Verified claims: REPOSITORY_IDENTITY, DEPENDENCY_VULNERABILITY_STATE. Insufficient evidence: BUILD_PROVENANCE. Unknown means SPR does not have enough evidence to make the claim — it is not a statement that the software is unsafe."
          policyVersion="1.0.0"
          reasonCodes={['POLICY_SATISFIED', 'INSUFFICIENT_INDEPENDENT_SOURCES', 'REQUIRED_EVIDENCE_MISSING']}
          observationCount={1299}
          evidenceReferenceCount={6}
          independentSourceCount={2}
          targetIdentity="df476048d023ff868cd45b35ee47f5fb0ca2b25a"
        />

        <GlassPanel className="p-6">
          <SectionHeader
            index="03"
            title="Why this decision"
            description="Each claim is evaluated on its own evidence. A claim is only verified when an independent third-party source supports it — SPR observing its own output never counts as corroboration."
          />
          <ul className="space-y-3">
            {SAMPLE_CLAIMS.map((item) => (
              <li key={item.claim} className="flex flex-wrap items-center gap-3 rounded-lg border border-[var(--cc-hairline)] p-3.5">
                <DecisionBadge state={item.state} size="sm" />
                <span className="cc-mono text-xs text-[var(--cc-ink)]">{item.claim}</span>
                <span className="min-w-[16rem] flex-1 text-xs text-[var(--cc-ink-muted)]">{item.note}</span>
              </li>
            ))}
          </ul>
        </GlassPanel>

        <GlassPanel className="p-6">
          <SectionHeader
            index="04"
            title="Evidence"
            description="Observations, not conclusions. Each record carries its source, collection time and content hash so a reviewer can check it rather than trust it."
          />
          <div className="grid gap-3 md:grid-cols-2">
            {SAMPLE_EVIDENCE.map((item) => (
              <EvidenceCard
                key={item.id}
                name={item.name}
                type={item.type}
                source={item.source}
                party={item.party}
                observedAt={item.observedAt}
                hash={item.hash}
              />
            ))}
          </div>
          <p className="mt-4 text-xs text-[var(--cc-ink-faint)]">
            1,299 observations resolve to 6 unique evidence items from 2 independent sources. Repeated
            observations of the same source are not independent corroboration.
          </p>
        </GlassPanel>

        <GlassPanel className="p-6">
          <SectionHeader index="05" title="What would change this decision" />
          <ul className="space-y-2.5">
            {[
              'A signed publisher attestation establishing build provenance for this exact commit.',
              'An independent third-party source corroborating the dependency inventory.',
              'Re-observation once the vulnerability evidence passes its freshness window.',
            ].map((item) => (
              <li key={item} className="flex gap-3 text-sm leading-6 text-[var(--cc-ink-muted)]">
                <span aria-hidden="true" className="mt-2 h-1 w-1 shrink-0 rounded-full bg-[var(--cc-ink-faint)]" />
                <span>{item}</span>
              </li>
            ))}
          </ul>
          <div className="mt-6 flex flex-wrap gap-2.5">
            {['R101', 'R201', 'R301'].map((code) => <ReasonCode key={code} code={code} />)}
          </div>
        </GlassPanel>

        <GlassPanel raised className="flex flex-wrap items-center justify-between gap-4 p-6">
          <div>
            <h2 className="text-lg font-semibold">See this on your own software</h2>
            <p className="mt-1 text-sm text-[var(--cc-ink-muted)]">Submit a public GitHub repository and see what SPR can actually observe.</p>
          </div>
          <button onClick={onRunFreeReview} className="rounded-xl bg-[#0e639c] px-6 py-3 text-sm font-bold text-white hover:bg-[#1177bb]">
            Run a Free Review
          </button>
        </GlassPanel>

        <DemoBanner />
      </div>
    </div>
  );
}
