import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowUpRight, Box, CheckCircle2, ChevronRight, Cloud, Code2, Database, FileCheck2, Fingerprint, Layers3, Link2, LockKeyhole, Network, PlayCircle, Radio, Search, ShieldCheck, Sparkles, Users, X } from 'lucide-react';
import type { Alert, Client, Scan, SoftwarePassport } from '../types';
import PilotOnboardingChecklist from './PilotOnboardingChecklist';

interface Props { clients: Client[]; alerts: Alert[]; scans: Scan[]; passports: SoftwarePassport[]; findings?: unknown[]; dataStatus?: 'loading' | 'ready' | 'error'; role?: string; onNavigateTab: (path: string, itemId?: string) => void; onOpenQuickAction: (actionType: 'add-client' | 'register-passport' | 'scan-sbom') => void; }

const CONNECTORS = [
  { title: 'Code & supply chain', icon: Code2, items: ['GitHub', 'GitLab', 'Bitbucket', 'Package registries', 'SBOMs'] },
  { title: 'Cloud & runtime', icon: Cloud, items: ['AWS', 'Azure', 'Google Cloud', 'Kubernetes', 'Containers'] },
  { title: 'Identity & enterprise', icon: LockKeyhole, items: ['Microsoft', 'Google', 'Okta', 'ServiceNow', 'SaaS'] },
  { title: 'Security & evidence', icon: ShieldCheck, items: ['Advisories', 'Scanners', 'Certificates', 'Attestations', 'Provenance'] },
];

function evidenceCount(passports: SoftwarePassport[]) { return passports.reduce((n, p: any) => n + (Array.isArray(p.evidence) ? p.evidence.length : 0), 0); }
function verifiedEvidenceCount(passports: SoftwarePassport[]) { return passports.reduce((n, p: any) => n + (Array.isArray(p.evidence) ? p.evidence.filter((e: any) => String(e.status).toUpperCase() === 'VERIFIED').length : 0), 0); }

export default function EvidenceDashboardView({ clients, alerts, scans, passports, findings = [], dataStatus = 'ready', role, onNavigateTab, onOpenQuickAction }: Props) {
  // The checklist's steps (add a client, save repository credentials, pick a
  // plan) need Owner/Admin/Operator rights; showing it to Client/Viewer users
  // asked them to do things the API refuses (review finding, 2026-09-20).
  const canOnboard = !role || ['Owner', 'Admin', 'Operator'].includes(role);
  const [query, setQuery] = useState('');
  const [tourOpen, setTourOpen] = useState(false);
  const activeAlerts = alerts.filter(a => a.status !== 'Resolved');
  const metrics = useMemo(() => {
    const evidence = evidenceCount(passports);
    const verified = verifiedEvidenceCount(passports);
    const vulnerabilities = passports.reduce((n, p: any) => n + (Array.isArray(p.vulnerabilities) ? p.vulnerabilities.filter((v: any) => String(v.status).toLowerCase() === 'open').length : 0), 0);
    const highFindings = (findings as any[]).filter(f => ['critical', 'high'].includes(String(f?.severity || '').toLowerCase()) && !['resolved', 'closed', 'verified'].includes(String(f?.status || '').toLowerCase())).length;
    const evidenceBearing = passports.filter((p: any) => Array.isArray(p.evidence) || Array.isArray(p.sbom) || Array.isArray(p.timeline)).length;
    return { evidence, verified, vulnerabilities, highFindings, evidenceBearing };
  }, [findings, passports]);
  const results = useMemo(() => { const q = query.trim().toLowerCase(); return q ? passports.filter((p: any) => `${p.name} ${p.version} ${p.publisher}`.toLowerCase().includes(q)).slice(0, 6) : []; }, [passports, query]);
  const attention = useMemo(() => [
    ...activeAlerts.filter((a: any) => String(a.severity || '').toLowerCase() === 'critical').map((a: any) => ({ id: String(a.id), title: a.title || a.name || 'Critical alert', detail: a.description || 'Active monitoring alert', path: '/monitoring' })),
    ...(findings as any[]).filter(f => ['critical', 'high'].includes(String(f?.severity || '').toLowerCase()) && !['resolved', 'closed', 'verified'].includes(String(f?.status || '').toLowerCase())).slice(0, 5).map(f => ({ id: String(f.id), title: f.title || f.name || 'Open finding', detail: f.description || `${f.severity || 'High'} severity finding`, path: '/security' })),
  ].slice(0, 6), [activeAlerts, findings]);

  return <div className="space-y-6 pb-10">
    {/* Renders itself only while a setup step is still open; see the component. */}
    {canOnboard && <PilotOnboardingChecklist
      clientsCount={clients.length}
      passportsCount={passports.length}
      scansCount={scans.length}
      onOpenQuickAction={onOpenQuickAction}
      onNavigateTab={onNavigateTab}
    />}
    <section className="spr-panel p-6 md:p-9"><div className="mb-4 flex flex-wrap items-center gap-2 text-[11px]"><span className={`rounded-sm border px-2.5 py-1 font-semibold uppercase tracking-[.14em] ${dataStatus === 'error' ? 'border-[var(--spr-red)]/40 bg-[var(--spr-red)]/10 text-[var(--spr-red)]' : dataStatus === 'loading' ? 'border-[var(--spr-amber)]/40 bg-[var(--spr-amber)]/10 text-[var(--spr-amber)]' : 'border-[var(--spr-border)] bg-[var(--spr-surface-alt)] text-[var(--spr-text-faint)]'}`}>{dataStatus === 'error' ? 'Data unavailable' : dataStatus === 'loading' ? 'Loading tenant records…' : 'Tenant records loaded'}</span>{dataStatus === 'error' && <button type="button" onClick={() => window.dispatchEvent(new Event('refresh-data'))} className="spr-btn spr-btn-secondary px-3 py-1.5 text-[11px]">Retry</button>}</div><div className="grid gap-8 xl:grid-cols-[1.35fr_.65fr] xl:items-end"><div>
      <div className="mb-4 flex flex-wrap gap-2 text-[11px] font-bold uppercase tracking-[.2em] text-[var(--spr-highlight)]"><span className="rounded-sm border border-[var(--spr-border)] bg-[var(--spr-accent-soft)] px-3 py-1.5">SPR Overview</span><span className="rounded-sm border border-[var(--spr-border)] px-3 py-1.5 text-[var(--spr-text-faint)]">Evidence-first</span></div>
      <h1 className="max-w-4xl text-4xl font-semibold tracking-[-.045em] md:text-6xl">Your software trust system, at a glance.</h1>
      <p className="mt-5 max-w-3xl text-base leading-7 text-[var(--spr-text-muted)] md:text-lg">One operating view for clients, software identities, evidence, findings and monitoring. Metrics below are derived from records loaded into this workspace.</p>
      <div className="mt-7 flex flex-wrap gap-3"><button onClick={() => onNavigateTab('/integrations')} className="spr-btn spr-btn-primary inline-flex items-center gap-2"><Link2 className="h-4 w-4"/> Connect systems</button><button onClick={() => setTourOpen(true)} className="spr-btn spr-btn-secondary inline-flex items-center gap-2"><PlayCircle className="h-4 w-4"/> How SPR works</button></div>
    </div><div className="spr-panel-alt p-5"><div className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.2em] text-[var(--spr-text-faint)]"><Radio className="h-3.5 w-3.5 text-[var(--spr-highlight)]"/> Live workspace</div><div className="mt-5 flex items-end justify-between"><div><div className="text-3xl font-semibold">Observed</div><div className="mt-1 text-xs text-[var(--spr-text-faint)]">Loaded tenant records</div></div><CheckCircle2 className="h-6 w-6 text-[var(--spr-highlight)]"/></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric value={clients.length} label="clients"/><Metric value={passports.length} label="software"/><Metric value={activeAlerts.length} label="attention"/></div></div></div></section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><HealthTile icon={Users} label="Clients" value={String(clients.length)} onClick={() => onNavigateTab('/clients')}/><HealthTile icon={Box} label="Software identities" value={String(passports.length)} onClick={() => onNavigateTab('/passports')}/><HealthTile icon={FileCheck2} label="Evidence" value={String(metrics.evidence)} onClick={() => onNavigateTab('/evidence-explorer')}/><HealthTile icon={AlertTriangle} label="Open attention" value={String(activeAlerts.length + metrics.highFindings)} danger={activeAlerts.length + metrics.highFindings > 0} onClick={() => onNavigateTab('/monitoring')}/><HealthTile icon={Fingerprint} label="Verified evidence" value={`${metrics.verified} / ${metrics.evidence}`} onClick={() => onNavigateTab('/security')}/></section>

    <section className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><div className="spr-panel p-6"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-semibold">Portfolio posture</div><div className="mt-1 text-xs text-[var(--spr-text-faint)]">Evidence, findings and vulnerability signals.</div></div><button onClick={() => onNavigateTab('/reports')} className="text-xs font-semibold text-[var(--spr-highlight)]">Open reports →</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Posture icon={FileCheck2} label="Software carrying evidence" value={`${metrics.evidenceBearing} of ${passports.length}`} detail="Evidence presence, not completeness."/><Posture icon={Fingerprint} label="Independently verified evidence" value={`${metrics.verified} of ${metrics.evidence}`} detail="Only records explicitly marked VERIFIED."/><Posture icon={AlertTriangle} label="High / critical findings" value={String(metrics.highFindings)} detail="Unresolved findings currently loaded." danger={metrics.highFindings > 0}/><Posture icon={Activity} label="Open vulnerabilities" value={String(metrics.vulnerabilities)} detail="Open vulnerability records attached to passports." danger={metrics.vulnerabilities > 0}/></div></div>
      <div className="spr-panel p-6"><div className="flex items-start justify-between gap-4"><div><div className="text-xs font-semibold">Needs attention</div><div className="mt-1 text-xs text-[var(--spr-text-faint)]">Operational items requiring investigation.</div></div><button onClick={() => onNavigateTab('/monitoring')} className="text-xs font-semibold text-[var(--spr-highlight)]">View all →</button></div><div className="mt-5 space-y-2">{attention.length ? attention.map(item => <button key={`${item.path}-${item.id}`} onClick={() => onNavigateTab(item.path, item.id)} className="group flex w-full items-center gap-3 rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] p-3 text-left hover:bg-[var(--spr-surface-hover)]"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-md bg-[var(--spr-accent-soft)]"><AlertTriangle className="h-4 w-4 text-[var(--spr-amber)]"/></span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{item.title}</span><span className="mt-1 block truncate text-[11px] text-[var(--spr-text-faint)]">{item.detail}</span></span><ChevronRight className="h-4 w-4 text-[var(--spr-text-faint)] group-hover:text-[var(--spr-highlight)]"/></button>) : <div className="rounded-md border border-dashed border-[var(--spr-border)] p-6 text-center"><CheckCircle2 className="mx-auto h-5 w-5 text-[var(--spr-highlight)]"/><p className="mt-2 text-sm font-semibold">No high-severity attention loaded</p><p className="mt-1 text-xs text-[var(--spr-text-faint)]">This reflects available records; it is not a certification.</p></div>}</div></div></section>

    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Surface icon={Network} title="Trust network" value={`${clients.length} clients`} text="See client-to-software relationships and trust state." onClick={() => onNavigateTab('/msp')}/><Surface icon={Database} title="Evidence fabric" value={`${scans.length} observations`} text="Inspect source evidence behind software records." onClick={() => onNavigateTab('/evidence-explorer')}/><Surface icon={Activity} title="Monitoring" value={`${activeAlerts.length} active`} text="Track changes, alerts and emerging attention." onClick={() => onNavigateTab('/monitoring')}/><Surface icon={Layers3} title="Reports" value="Operational" text="Turn observed state into client-ready reporting." onClick={() => onNavigateTab('/reports')}/></section>

    <section className="grid gap-6 xl:grid-cols-[1fr_1.1fr]"><div className="spr-panel p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold">Connect the ecosystem</div><div className="mt-1 text-xs text-[var(--spr-text-faint)]">Bring the systems that build, ship, run and govern software.</div></div><button onClick={() => onNavigateTab('/integrations')} className="text-xs font-semibold text-[var(--spr-highlight)]">View connectors →</button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{CONNECTORS.map(({ title, icon: Icon, items }) => <div key={title} className="rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] p-4"><div className="flex items-center gap-2 text-xs font-semibold"><Icon className="h-4 w-4 text-[var(--spr-highlight)]"/>{title}</div><div className="mt-3 flex flex-wrap gap-1.5">{items.map(item => <span key={item} className="rounded-sm border border-[var(--spr-border)] bg-[var(--spr-surface-sunken)] px-2 py-1 text-[12px] text-[var(--spr-text-muted)]">{item}</span>)}</div></div>)}</div></div>
      <div className="spr-panel p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold">Software registry</div><div className="mt-1 text-xs text-[var(--spr-text-faint)]">Jump directly into a software identity.</div></div><button onClick={() => onNavigateTab('/passports')} className="text-xs font-semibold text-[var(--spr-highlight)]">Open registry →</button></div><div className="relative mt-5"><Search className="absolute left-3 top-3 h-4 w-4 text-[var(--spr-text-faint)]"/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search software, publisher, version…" className="w-full rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-sunken)] py-3 pl-10 pr-4 text-sm outline-none placeholder:text-[var(--spr-text-faint)] focus:border-[var(--spr-highlight)]"/>{results.length > 0 && <div className="absolute left-0 right-0 top-14 z-20 spr-panel-alt overflow-hidden p-2">{results.map((p: any) => <button key={p.id} onClick={() => onNavigateTab('/passports', String(p.id))} className="flex w-full items-center gap-3 rounded-md px-3 py-3 text-left hover:bg-[var(--spr-surface-hover)]"><Box className="h-4 w-4 text-[var(--spr-highlight)]"/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{p.name}</span><span className="block truncate text-[11px] text-[var(--spr-text-faint)]">{p.publisher || 'Unknown publisher'} · {p.version || 'unknown version'}</span></span><ArrowUpRight className="h-4 w-4 text-[var(--spr-text-faint)]"/></button>)}</div>}</div><div className="mt-5 grid grid-cols-3 gap-2"><Mini label="Clients" value={clients.length}/><Mini label="Passports" value={passports.length}/><Mini label="Scans" value={scans.length}/></div></div></section>

    <section className="spr-panel p-6 md:p-7"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold"><Sparkles className="h-4 w-4 text-[var(--spr-highlight)]"/> One operating system for trust</div><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--spr-text-muted)]">Overview shows the state. MSP operates the portfolio. Evidence supports claims. Passports identify software. Monitoring detects change. Reports communicate observed state.</p></div><button onClick={() => onNavigateTab('/msp')} className="spr-btn spr-btn-secondary inline-flex shrink-0 items-center gap-2">Open MSP Command <ArrowUpRight className="h-4 w-4"/></button></div></section>

    {tourOpen && <div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4"><div className="w-full max-w-xl spr-panel p-7"><div className="flex items-center justify-between"><div className="text-[11px] font-bold uppercase tracking-[.2em] text-[var(--spr-highlight)]">Overview guide</div><button onClick={() => setTourOpen(false)} aria-label="Close" title="Close"><X className="h-4 w-4 text-[var(--spr-text-faint)]"/></button></div><h2 className="mt-7 text-3xl font-semibold">From overview to operation.</h2><div className="mt-6 space-y-3"><Guide n="01" title="Discover" text="Build durable software identities from the systems around you."/><Guide n="02" title="Collect evidence" text="Keep observations tied to their sources and expose uncertainty."/><Guide n="03" title="Operate" text="Use monitoring and findings to work exceptions."/><Guide n="04" title="Communicate" text="Use passports and reports to make observed state portable."/></div><div className="mt-7 flex justify-end"><button onClick={() => setTourOpen(false)} className="spr-btn spr-btn-primary">Enter overview</button></div></div></div>}
  </div>;
}
function Metric({ value, label }: { value: number; label: string }) { return <div className="rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] px-2 py-2"><div className="text-sm font-semibold">{value}</div><div className="text-[11px] uppercase tracking-[.15em] text-[var(--spr-text-faint)]">{label}</div></div>; }
function HealthTile({ icon: Icon, label, value, onClick, danger = false }: { icon: any; label: string; value: string; onClick: () => void; danger?: boolean }) { return <button onClick={onClick} className="group rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] p-4 text-left transition hover:bg-[var(--spr-surface-hover)]"><div className="flex items-center justify-between"><Icon className={`h-4 w-4 ${danger ? 'text-[var(--spr-red)]' : 'text-[var(--spr-highlight)]'}`}/><ArrowUpRight className="h-3.5 w-3.5 text-[var(--spr-text-faint)] group-hover:text-[var(--spr-highlight)]"/></div><div className={`mt-3 text-xl font-semibold ${danger ? 'text-[var(--spr-red)]' : ''}`}>{value}</div><div className="mt-1 text-[11px] uppercase tracking-[.14em] text-[var(--spr-text-faint)]">{label}</div></button>; }
function Posture({ icon: Icon, label, value, detail, danger = false }: { icon: any; label: string; value: string; detail: string; danger?: boolean }) { return <div className="rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] p-4"><div className="flex items-start gap-3"><Icon className={`mt-0.5 h-4 w-4 ${danger ? 'text-[var(--spr-red)]' : 'text-[var(--spr-highlight)]'}`}/><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold">{label}</span><span className={`text-sm font-semibold ${danger ? 'text-[var(--spr-red)]' : ''}`}>{value}</span></div><p className="mt-1 text-[11px] leading-5 text-[var(--spr-text-faint)]">{detail}</p></div></div></div>; }
function Surface({ icon: Icon, title, value, text, onClick }: { icon: any; title: string; value: string; text: string; onClick: () => void }) { return <button onClick={onClick} className="group rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] p-5 text-left transition hover:bg-[var(--spr-surface-hover)]"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-sunken)]"><Icon className="h-4 w-4 text-[var(--spr-highlight)]"/></span><ArrowUpRight className="h-4 w-4 text-[var(--spr-text-faint)] group-hover:text-[var(--spr-highlight)]"/></div><div className="mt-5 text-xs font-semibold">{title}</div><div className="mt-1 text-lg font-semibold text-[var(--spr-highlight)]">{value}</div><p className="mt-2 text-[11px] leading-5 text-[var(--spr-text-muted)]">{text}</p></button>; }
function Mini({ label, value }: { label: string; value: number }) { return <div className="rounded-md border border-[var(--spr-border)] bg-[var(--spr-surface-alt)] p-3"><div className="text-lg font-semibold">{value}</div><div className="text-[10px] uppercase tracking-[.14em] text-[var(--spr-text-faint)]">{label}</div></div>; }
function Guide({ n, title, text }: { n: string; title: string; text: string }) { return <div className="flex gap-4 rounded-md border border-[var(--spr-border)] p-4"><span className="text-xs font-bold text-[var(--spr-highlight)]">{n}</span><div><div className="text-sm font-semibold">{title}</div><div className="mt-1 text-xs leading-5 text-[var(--spr-text-muted)]">{text}</div></div></div>; }
