import { useCallback,useEffect,useState } from 'react';
import { apiFetch } from '../utils/apiClient';
type Cell={id:string;name:string;source:string;state:string;control:string;counts:Record<string,number>;last:{id:string;last_error:string|null;result:{metrics:Record<string,unknown>;observedAt:string}|null}|null};
type Payload={cells:Cell[];generatedAt:string;receipts:{id:string;cell_id:string;previous_state:string;next_state:string;reason:string}[]};
export default function FounderGrowthCells(){
 const [data,setData]=useState<Payload|null>(null);const [selected,setSelected]=useState('recon');const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const response=await apiFetch('/api/founder/growth-cells');if(!response.ok)throw new Error(`Cells unavailable (${response.status})`);setData(await response.json());setError(null);}catch(err){setData(null);setError(err instanceof Error?err.message:'Cells unavailable');}},[]);
 useEffect(()=>{void load();const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load();},30000);return()=>window.clearInterval(timer);},[load]);
 const cell=data?.cells.find(item=>item.id===selected);
 const act=async(state?:string)=>{if(!cell)return;setBusy(true);try{const response=await apiFetch(`/api/founder/growth-cells/${cell.id}${state?'':'/missions'}`,state?{method:'PATCH',body:JSON.stringify({state,reason})}:{method:'POST'});const body=await response.json();if(!response.ok)throw new Error(body.error??'Cell action failed');setReason('');await load();}catch(err){setError(err instanceof Error?err.message:'Cell action failed');}finally{setBusy(false);}};
 return <section aria-label="Growth Command cells" className="rounded-2xl border border-cyan-500/30 bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 p-6 text-slate-100">
 <div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-cyan-300">SPR Growth Command</p><h2 className="mt-2 text-2xl font-semibold">Your cell command center</h2></div><button type="button" onClick={()=>void load()} className="rounded-lg border border-cyan-400/40 px-4 py-2">Refresh evidence</button></div>
 <p className="mt-3 text-sm text-slate-300">Select a cell to run a durable observation mission against SPR records. Outreach continues through existing campaign controls. Recorded customer stages do not prove payment.</p>
 <p className="mt-2 text-xs text-slate-400">{data?`Observed ${new Date(data.generatedAt).toLocaleString()}`:'Activity UNKNOWN'} · Costs UNKNOWN · Automated publishing, ad buying, cell chat and specialist replacement are not implemented.</p>
 {error&&<p role="alert" className="mt-4 text-rose-300">{error}</p>}
 <div className="mt-6 grid gap-5 lg:grid-cols-[1.5fr_1fr]"><div className="grid content-start gap-3 sm:grid-cols-3">{data?.cells.map(item=><button type="button" key={item.id} aria-pressed={selected===item.id} onClick={()=>setSelected(item.id)} className={`rounded-xl border p-4 text-left ${selected===item.id?'border-cyan-300 bg-cyan-400/10':'border-slate-700 bg-slate-900/70'}`}><strong className="block">{item.name}</strong><span className="mt-2 block text-xs text-cyan-200">{item.state}</span><span className="mt-2 block text-xs text-slate-400">{item.counts.queued} queued · {item.counts.running} running</span></button>)}</div>
 {cell&&<div className="rounded-xl border border-cyan-500/30 bg-slate-950/60 p-5"><h3 className="text-xl font-semibold">{cell.name}</h3><p className="mt-3 text-xs text-slate-400">Source: {cell.source} · Mission: {cell.last?.id??'None observed'}</p><dl className="mt-4 space-y-2">{Object.entries(cell.counts).map(([key,value])=><div key={key} className="flex justify-between"><dt>{key}</dt><dd>{value}</dd></div>)}</dl>{cell.last?.last_error&&<p className="mt-3 text-rose-300">{cell.last.last_error}</p>}{cell.last?.result&&<dl className="mt-4 space-y-2 text-sm">{Object.entries(cell.last.result.metrics).map(([key,value])=><div key={key} className="flex flex-wrap justify-between gap-2"><dt className="text-slate-400">{key}</dt><dd>{value==null?'UNKNOWN':String(value)}</dd></div>)}</dl>}
 <button type="button" disabled={busy||cell.control!=='observing'||cell.counts.queued+cell.counts.running>0} onClick={()=>void act()} className="mt-5 w-full rounded-lg bg-cyan-300 p-3 font-semibold text-slate-950 disabled:opacity-40">Launch observation mission</button>
 <label className="mt-5 block text-sm">Control change reason<input value={reason} maxLength={500} onChange={event=>setReason(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-600 bg-slate-900 p-2"/></label><div className="mt-3 flex flex-wrap gap-2">{[['observing','Resume observations'],['paused','Pause'],['archived','Archive']].map(([state,label])=><button type="button" key={state} disabled={busy||reason.trim().length<3||cell.control===state} onClick={()=>void act(state)} className="rounded-lg border border-slate-600 p-2 text-xs disabled:opacity-40">{label}</button>)}</div><p className="mt-3 text-xs text-slate-400">Pause/archive stops future observation claims. An already running mission may finish. Outreach campaign controls remain separate.</p></div>}</div>
 <h3 className="mt-6 font-semibold">Control receipts</h3><ul className="mt-3 space-y-2">{data?.receipts.map(receipt=><li key={receipt.id} className="rounded-lg border border-slate-700 p-3 text-sm">{receipt.cell_id}: {receipt.previous_state} → {receipt.next_state} · {receipt.reason}<span className="block text-xs text-slate-400">{receipt.id}</span></li>)}</ul>{data?.receipts.length===0&&<p className="mt-2 text-sm text-slate-400">No control changes recorded.</p>}
 </section>;
}
