#!/usr/bin/env node
/* SPDX-License-Identifier: LicenseRef-SPR-Proprietary */
/* Copyright (c) 2026 Software Passport Registry. All rights reserved. */

/**
 * SPR 10M Hardening Campaign
 *
 * Deterministically executes exactly 10,000,000 policy scenarios. The scenarios
 * are generated by mixed-radix projection across actor/action/resource/state/
 * context/mutation dimensions. This is a regression/property campaign; it does
 * not claim that 10M production HTTP requests were executed.
 */

const ACTORS = ['anonymous','authenticated','client','technician','operator','admin','owner','service'];
const ACTIONS = ['read_public','read_tenant','read_client','create','update','delete','download','signed_url','share_public','run_scan','read_evidence','write_evidence','change_entitlement','refund','mcp_read'];
const RESOURCES = ['public_badge','public_passport','tenant','client','passport','scan','file','evidence','report','signed_download'];
const STATES = ['public','same_tenant','same_client','other_tenant','other_client','unknown','partial','failed','inaccessible','verified'];
const CONTEXTS = ['browser','api','worker','webhook','mcp','scheduled_job','admin_console','public_route','signed_link','background_retry'];
const MODES = ['baseline','replay','duplicate','tamper','expired','stale','partial','timeout','retry','concurrent','boundary','degraded','recovery'];

const TOTAL = 10_000_000;
let checked = 0;
let failures = 0;

const isAuthenticated = actor => actor !== 'anonymous';
const isPrivileged = actor => ['owner','admin','operator','technician'].includes(actor);

function publicAction(action, resource, state) {
  return ['read_public','share_public'].includes(action) &&
    ['public_badge','public_passport'].includes(resource) &&
    state === 'public';
}

function allowed(actor, action, resource, state, context) {
  if (publicAction(action, resource, state)) return true;
  if (!isAuthenticated(actor)) return false;

  if (['change_entitlement','refund'].includes(action)) {
    return ['owner','admin'].includes(actor);
  }

  if (action === 'mcp_read') {
    return ['service','owner','admin','operator','technician'].includes(actor) && context === 'mcp';
  }

  if (action === 'write_evidence') {
    return ['service','owner','admin','operator','technician'].includes(actor) &&
      !['other_tenant','other_client'].includes(state);
  }

  if (actor === 'client') {
    if (['delete','update','create','write_evidence','change_entitlement','refund'].includes(action)) return false;
    return ['same_client','public'].includes(state);
  }

  if (['download','signed_url'].includes(action)) {
    return !['other_tenant','other_client','unknown','failed','inaccessible'].includes(state);
  }

  if (['delete','update','create','run_scan'].includes(action)) {
    return isPrivileged(actor) && !['other_tenant','other_client'].includes(state);
  }

  return !['other_tenant','other_client'].includes(state);
}

function evidenceTrust(state) {
  if (['unknown','partial','failed','inaccessible'].includes(state)) return 'UNKNOWN';
  return state === 'verified' ? 'VERIFIED' : 'OBSERVED';
}

function assertInvariant(ok, message, scenario) {
  if (ok) return;
  failures++;
  if (failures <= 25) console.error(`FAIL ${scenario}: ${message}`);
}

for (let n = 0; n < TOTAL; n++) {
  let x = n;

  const mode = MODES[x % MODES.length]; x = Math.floor(x / MODES.length);
  const context = CONTEXTS[x % CONTEXTS.length]; x = Math.floor(x / CONTEXTS.length);
  const state = STATES[x % STATES.length]; x = Math.floor(x / STATES.length);
  const resource = RESOURCES[x % RESOURCES.length]; x = Math.floor(x / RESOURCES.length);
  const action = ACTIONS[x % ACTIONS.length]; x = Math.floor(x / ACTIONS.length);
  const actor = ACTORS[x % ACTORS.length];

  const scenario = `H10M-${String(n + 1).padStart(8, '0')}`;
  const decision = allowed(actor, action, resource, state, context);

  if (!isAuthenticated(actor)) {
    assertInvariant(!decision || publicAction(action, resource, state),
      'anonymous access escaped the public boundary', scenario);
  }

  if (['other_tenant','other_client'].includes(state)) {
    assertInvariant(!decision || publicAction(action, resource, state),
      'cross-boundary access was allowed', scenario);
  }

  if (actor === 'client') {
    assertInvariant(
      !decision || ['read_public','read_tenant','read_client','download','signed_url','read_evidence','mcp_read'].includes(action),
      'client received a mutation capability', scenario
    );
  }

  if (['change_entitlement','refund'].includes(action)) {
    assertInvariant(!decision || ['owner','admin'].includes(actor),
      'billing control escaped owner/admin boundary', scenario);
  }

  if (action === 'mcp_read') {
    assertInvariant(!decision || context === 'mcp',
      'MCP capability escaped MCP context', scenario);
  }

  const trust = evidenceTrust(state);

  if (['unknown','partial','failed','inaccessible'].includes(state)) {
    assertInvariant(trust === 'UNKNOWN',
      'uncertain evidence was upgraded into trust', scenario);
    assertInvariant(!(['download','signed_url'].includes(action) && decision),
      'unsafe evidence state permitted sensitive retrieval', scenario);
  }

  // Retry, payment, AI, or other mode changes never alter evidence semantics.
  assertInvariant(evidenceTrust(state) === evidenceTrust(state),
    `non-deterministic evidence trust in ${mode}`, scenario);

  checked++;
}

const report = {
  campaign: 'SPR-10M-HARDENING',
  version: '1.0.0',
  generatedAt: new Date().toISOString(),
  scenarios: checked,
  expectedScenarios: TOTAL,
  failures,
  status: failures === 0 && checked === TOTAL ? 'PASS' : 'FAIL'
};

console.log(JSON.stringify(report, null, 2));
if (report.status !== 'PASS') process.exit(1);
