import path from 'node:path';
export const FILE_LIMITS = Object.freeze({ maxSingleFileBytes: 50 * 1024 * 1024, maxArchiveBytes: 100 * 1024 * 1024, maxExpandedArchiveBytes: 500 * 1024 * 1024, maxArchiveEntries: 10_000, maxFilenameBytes: 255, maxPathDepth: 32 });
export type FileDisposition = 'DISCOVERED' | 'INVENTORIED' | 'INSPECTED' | 'PARTIAL' | 'UNSUPPORTED' | 'SKIPPED' | 'FAILED' | 'INACCESSIBLE' | 'ANALYZED';
const CONTROL_OR_DANGEROUS = /[\u0000-\u001f\u007f]/;
export function validateUploadSize(size: number, archive = false): void { if (!Number.isSafeInteger(size) || size < 0) throw new Error('FILE_SIZE_INVALID'); const max = archive ? FILE_LIMITS.maxArchiveBytes : FILE_LIMITS.maxSingleFileBytes; if (size > max) throw new Error('FILE_SIZE_LIMIT_EXCEEDED'); }
export function sanitizeDisplayFilename(input: string): string { if (typeof input !== 'string' || !input || input.length > FILE_LIMITS.maxFilenameBytes) throw new Error('FILENAME_INVALID'); if (CONTROL_OR_DANGEROUS.test(input)) throw new Error('FILENAME_INVALID'); const normalized = input.replaceAll('\\\\', '/'); const base = path.basename(normalized); if (!base || base === '.' || base === '..' || base !== normalized) throw new Error('FILENAME_PATH_COMPONENT_BLOCKED'); return base.replace(/[^A-Za-z0-9._ -]/g, '_'); }
export function safeArchiveEntryPath(root: string, entryName: string): string { if (typeof entryName !== 'string' || !entryName || CONTROL_OR_DANGEROUS.test(entryName)) throw new Error('ARCHIVE_ENTRY_INVALID'); const normalized = entryName.replaceAll('\\\\', '/'); if (normalized.startsWith('/') || /^[A-Za-z]:\//.test(normalized)) throw new Error('ARCHIVE_ABSOLUTE_PATH_BLOCKED'); const segments = normalized.split('/').filter(Boolean); if (segments.some(segment => segment === '..')) throw new Error('ARCHIVE_TRAVERSAL_BLOCKED'); if (segments.length > FILE_LIMITS.maxPathDepth) throw new Error('ARCHIVE_PATH_DEPTH_EXCEEDED'); const targetRoot = path.resolve(root); const target = path.resolve(targetRoot, ...segments); const relative = path.relative(targetRoot, target); if (relative === '..' || relative.startsWith('..' + path.sep) || path.isAbsolute(relative)) throw new Error('ARCHIVE_TRAVERSAL_BLOCKED'); return target; }
export function validateArchiveManifest(entries: readonly { name: string; compressedSize?: number; uncompressedSize?: number; isSymlink?: boolean }[]): void { if (entries.length > FILE_LIMITS.maxArchiveEntries) throw new Error('ARCHIVE_ENTRY_LIMIT_EXCEEDED'); let expanded = 0; for (const entry of entries) { if (entry.isSymlink) throw new Error('ARCHIVE_SYMLINK_BLOCKED'); safeArchiveEntryPath('/spr-safe-extraction', entry.name); const expandedSize = entry.uncompressedSize ?? entry.compressedSize ?? 0; if (!Number.isSafeInteger(expandedSize) || expandedSize < 0) throw new Error('ARCHIVE_SIZE_INVALID'); expanded += expandedSize; if (expanded > FILE_LIMITS.maxExpandedArchiveBytes) throw new Error('ARCHIVE_EXPANDED_SIZE_LIMIT_EXCEEDED'); } }
export function detectMagicType(bytes: Uint8Array): 'zip' | 'gzip' | 'pdf' | 'png' | 'unknown' { if (bytes.length >= 4 && bytes[0] === 0x50 && bytes[1] === 0x4b && bytes[2] === 0x03 && bytes[3] === 0x04) return 'zip'; if (bytes.length >= 2 && bytes[0] === 0x1f && bytes[1] === 0x8b) return 'gzip'; if (bytes.length >= 4 && bytes[0] === 0x25 && bytes[1] === 0x50 && bytes[2] === 0x44 && bytes[3] === 0x46) return 'pdf'; if (bytes.length >= 8 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47 && bytes[4] === 0x0d && bytes[5] === 0x0a && bytes[6] === 0x1a && bytes[7] === 0x0a) return 'png'; return 'unknown'; }
export function assertDeclaredTypeMatchesMagic(declared: string, bytes: Uint8Array): void { const magic = detectMagicType(bytes); if (magic === 'unknown') return; const allowed: Record<string, string[]> = { 'application/zip': ['zip'], 'application/gzip': ['gzip'], 'application/pdf': ['pdf'], 'image/png': ['png'] }; if (allowed[declared] && !allowed[declared].includes(magic)) throw new Error('FILE_MAGIC_TYPE_MISMATCH'); }